### ISSUE TITLE
'generator-jhipster-nodejs@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by akulinski** [jhipster/generator-jhipster-nodejs#1]
## Overview of the issue
Generator installation fails with Not Found - GET https://registry.npmjs.org/generator-jhipster-nodejs - Not found

## Reproduce the error
npm install -g generator-jhipster-nodejs

## JHipster Version(s)
5.8.2

[node.log](https://github.com/jhipster/generator-jhipster-nodejs/files/3292132/node.log)

![node](https://user-images.githubusercontent.com/28159652/59536437-021b0380-8ef4-11e9-8d51-9b325e0cc77b.jpg)

**Comment by amanganiello90** [comment]
Hi @akulinski, the generator isn't published yet because is a working progress.

**Comment by hadirsa** [comment]
@amanganiello90  So how we can test it?

**Comment by amanganiello90** [comment]
@hadirsa, now the generator doesn't have any features (has only the initial commit of blueprint scaffolder). So consider the [conributin guide](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/CONTRIBUTING.md) to install, develop and try it
