### ISSUE TITLE
copying node modules - support webpack bundle

### ISSUE THREAD

**Issue by kosnkow** [jhipster/generator-jhipster-nodejs#100]
hi, this is not a bug but rather the question, 
is it really necessery to move all node modules to hosting server when deploying the app ?
we moved only dist folder to the hosting server without node modules and the app started requring module after module, so we moved all node modules and the app started working .

**Comment by amanganiello90** [comment]
Hi @kosnkow , you are welcome! feel free to open issues for every feature/bug/question.
So, for now it's necessary to have the node_modules.
A few days ago I thought a packaging with webpack compressing node_modules modules in the main.js, but now it's not possible because there are some native modules (.bat, .sh and .node) under node_modules folder that raise error in webpack.

**Comment by amanganiello90** [comment]
Hi @kosnkow , I'm working for the feature with webpack, that produces a prod bundle without node_modules requirement. I have to test better that, but it seems to work, without sqlite native dev dependency.

You can download [resolve-env branch](https://github.com/jhipster/generator-jhipster-nodejs/tree/bug/resolve-env) and follows these steps to use it: https://github.com/jhipster/generator-jhipster-nodejs/tree/bug/resolve-env#-steps-to-develop-a-generator-feature-and-test-it

**Comment by amanganiello90** [comment]
Hi @kosnkow ,
you can test the new version just published [1.0.0-beta.3](https://www.npmjs.com/package/generator-jhipster-nodejs/v/1.0.0-beta.3). 

In that there is a new npm script in server package.json: **webpack:prod**. Run it, in the end you can copy all the **dist** folder in another directory without node_modules. Execute in your new dir:

- node dist/bundle.js

It will run the app for the prod env. So please attention to configure your prod db connection in [here](https://github.com/jhipster/jhipster-sample-app-nodejs/blob/master/server/src/orm.config.ts#L30).

Then, Tell me if there is all ok.

Feel free to open new issues if there are another problems. Thanks!

**Comment by kosnkow** [comment]
I confirm it works, bundle.js is 10M now, but no node_modules :)

**Comment by amanganiello90** [comment]
Hi @kosnkow,
Thanks for the feedback! but I don't understand the statement:

>then somhow java hipster took role and was kind of pushing me to create java project.

**Comment by amanganiello90** [comment]
I will close this issue, that I consider resolved. Thanks for the feedbacks
