### ISSUE TITLE
Protractor or another tool for client e2e tests

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#101]
Add default choose for client e2e tests

**Comment by mraible** [comment]
Can't you use the same client testing tool that the main generator uses? I'm not sure why a backend framework would need to override this.

**Comment by amanganiello90** [comment]
Hi @mraible , yes in fact the the issue is to apply protractor also for backend. The added title ("or onother tool") is to keep open the investigation if there is another tool more performant for nodejs.

**Comment by amanganiello90** [comment]
Hi @mraible . Finally I'm able to reach this feature. There is a lot of stuff done (I had to implement the user management api, fix nestJS routing with angular/react, run the e2e tests for admin and entities, create new tests and jobs for every combination in the pipelines).

Please check it. Every improvements and suggestions are welcome!

**Comment by amanganiello90** [comment]
$200 bug bounty claim: https://opencollective.com/generator-jhipster/expenses/28939
