### ISSUE TITLE
ci-cd for nodejs application

### ISSUE THREAD

**Issue by ajoysinhactc** [jhipster/generator-jhipster-nodejs#104]
If I run following command to generate jenkinsfile .

jhipster  ci-cd --blueprints nodejs

Jenkinsfile is generated but it is not for nodejs application, rather than it is for java application.
It seems to me that ci-cd for nodejs application has not been implemented yet. 

Following are the comment out of execution of generator command.

> INFO! No custom commands found within blueprint: generator-jhipster-nodejs
> INFO! Using JHipster version installed locally in current project's node_modules
> INFO! No custom commands found within blueprint: generator-jhipster-nodejs
> INFO! Executing jhipster:ci-cd
> INFO! Options: blueprints: nodejs, from-cli: true
> 🚀 Welcome to the JHipster CI/CD Sub-Generator 🚀
> ? What CI/CD pipeline do you want to generate? Jenkins pipeline
> ? Would you like to perform the build in a Docker container ? Yes
> ? Would you like to send build status to GitLab ? Yes
> ? What tasks/integrations do you want to include ? Build and publish a *Docker* image
> identical Jenkinsfile
> identical src\main\resources\idea.gdsl
> identical src\main\docker\jenkins.yml
> identical src\main\docker\docker-registry.yml
> INFO! Congratulations, JHipster execution is complete!

**Comment by amanganiello90** [comment]
Hi @ajoysinhactc, thanks for the issue!
Yes, the blueprint does not implement ci-cd submodule, so the command that you have run use the standard jhipster generation. If you want to contribute with the development or a donation you are welcome!

**Comment by amanganiello90** [comment]
@mraible I'm trying to customize [ci-cd subgenerator](https://github.com/jhipster/generator-jhipster-nodejs/blob/feature/ci-issue-104/generators/ci-cd/index.js), but I note that the jhipster ci-cd index.js file extends the [generator-base](https://github.com/jhipster/generator-jhipster/blob/ae893d0f6e53d648641d96ced0ab0f6058fbe29e/generators/ci-cd/index.js#L29), and not the generator-blueprint-base.So when I perform the **jhipster --blueprints nodejs ci-cd** command, always the jhipster ci-cd generator is called. Do you know a method to rewrite that? Thanks in advance.

**Comment by amanganiello90** [comment]
The development is stopped because we need before to update to jhipster 7

**Comment by amanganiello90** [comment]
$200 bug bounty claim: https://opencollective.com/generator-jhipster/expenses/47076

**Comment by pascalgrimaud** [comment]
@amanganiello90 : approved
