### ISSUE TITLE
import-jdl doesn't generate associate code

### ISSUE THREAD

**Issue by Zahma** [jhipster/generator-jhipster-nodejs#107]
**Describe the bug**
when running jhipster import-jdl 'my_file.jdl' --blueprints nodejs, nHipster doesn't generate the required entities. It says that master.xml from liquibase files doesn't exist.

**To Reproduce**
jhipster import-jdl my_file.jdl --blueprints nodejs

**Expected behavior**
Generate backend code

**Comment by amanganiello90** [comment]
Thanks for the feedback. Are you following the installations steps for the nodejs blueprint? Maybe it is not correctly installed because the generation runs with the standard jhipster phase.
In this repository there are all integration tests with jdl examples, so it is a machine configuration issue:  https://github.com/jhipster/generator-jhipster-nodejs/tree/master/test-integration/samples

**Comment by Zahma** [comment]
first of all I would like to thank you for your wonderful work.
Maybe its a problem related to the version of generator-jhipster that I use. I'm using the latest version 6.8.0, whereas in yout documentation I think its compatible with 6.6.0 ? I will retest with 6.6.0

**Comment by amanganiello90** [comment]
Thanks you for the contribution! it's my pleasure that the community start to grew up :) ..
Yes for now the jhipster version is 6.6.0

**Comment by Zahma** [comment]
I'm back I tested back with 6.6.0 still getting the same message:

Unable to find src/main/resources/config/liquibase/master.xml or missing required jhipster-needle. Reference to 20200310200041_added_entity_constraints_Accountant.xml not added.

for each of my entities and relationships.

**Comment by amanganiello90** [comment]
Are you be able to create the node js app with:
``jhipster - - blueprints nodejs```
?

**Comment by Zahma** [comment]
Yes I was able to create the app, then I run jhipster import-jdl dropme.jdl --blueprints nodejs

**Comment by amanganiello90** [comment]
Could you run with:

```jhipster --blueprints nodejs import-jdl dropme.jdl```
?
If you have error yet,  please attach here your jdl.

**Comment by Zahma** [comment]
The jdl is the one from https://www.jhipster.tech/jdl-studio/ the basic example.

**Comment by amanganiello90** [comment]
> 
> 
> The jdl is the one from https://www.jhipster.tech/jdl-studio/ the basic example.

Could you please install the nodejs blueprint as devDependency in your generated project with :
```npm install generator-jhipster-nodejs --save-dev```
And rerun import command?

**Comment by Zahma** [comment]
@amanganiello90 Well done now it works, Thank youu

**Comment by amanganiello90** [comment]
Thank you, I will reinclude blueprint as devDependency.
