### ISSUE TITLE
Problem with jdl relationships between default User jhipster entity

### ISSUE THREAD

**Issue by Zahma** [jhipster/generator-jhipster-nodejs#110]
**Describe the bug**
Generated code is not running because of one to one relationship with the entity user I guess.

**To Reproduce**
1. Generate code with the following JDL:

entity ExtendOne {

}

entity ExtendTwo {

}

relationship OneToOne {
    ExtendOne{user(login) required} to User,
    ExtendTwo{user(login) required} to User,
}

2. Start the app

**Expected behavior**
Getting the following error:
`    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/domain/extendOnet.entity.ts:6:8 - error TS1192: Module '"D:/dev/Projet_Mehdi/S/server/src/domain/user.entity"' has no default export.

6 import User from './user.entity';
         ~~~~
src/domain/extend-one.entity.ts:55:20 - error TS2339: Property 'extendOne' does not exist on type '{}'.

55     other => other.extendOne`

**Comment by amanganiello90** [comment]
Hi @Zahma  thanks for the feedback!
Maybe your jdl is wrong... you cannot do relationship with the dafault jhipster user.
Infact, in the running is logged a warn:
``
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
``

**Comment by Zahma** [comment]
Thank you, In fact the relationship points towards Users and not the opposite . So normally the relationship should be kept. Otherwise, do you know of a good idea to extend user entity ? In Jhipster we used to add the "mappedBy" in the user domain.

**Comment by MathieuAA** [comment]
The JDL is okay (except I don't get the two relationships, but I guess it's just an over-simplified sample).
Looks like a genuine compilation issue due to what's been generated, but it's weird: I could have sworn this use-case is supported in JHipster (without blueprint I mean)

**Comment by amanganiello90** [comment]
Maybe I have resolved this in: https://github.com/jhipster/generator-jhipster-nodejs/tree/bug/110

You can download and link locally that for testing. For me it's work. Thanks a lot

**Comment by amanganiello90** [comment]
> 
> 
> The JDL is okay (except I don't get the two relationships, but I guess it's just an over-simplified sample).
> Looks like a genuine compilation issue due to what's been generated, but it's weird: I could have sworn this use-case is supported in JHipster (without blueprint I mean)

Yes, I have fixed it.

**Comment by Zahma** [comment]
I'll try and let you know ;)

**Comment by amanganiello90** [comment]
> 
> 
> I'll try and let you know ;)

Sweet, thanks!

**Comment by amanganiello90** [comment]
I have retested it. So, in order to release, I consider this close. If you have other request please open a new issue. Thanks
