### ISSUE TITLE
First stable Release: 1.0.0

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#117]
This issue report the status update of the first stable (not beta) release.

**Comment by amanganiello90** [comment]
Here [CHANGELOG.md](https://github.com/jhipster/generator-jhipster-nodejs/blob/v1.0.0/CHANGELOG.md):

- Copying node modules - support webpack bundle [issue #100](https://github.com/jhipster/generator-jhipster-nodejs/issues/100)
-   ManyToOne relationship error generation [issue #106](https://github.com/jhipster/generator-jhipster-nodejs/issues/106)
-   Problem with jdl relationships between default User jhipster entity [issue #110](https://github.com/jhipster/generator-jhipster-nodejs/issues/110)
-   Support Keycloak docker image and configuration for oauth2 [issue #64](https://github.com/jhipster/generator-jhipster-nodejs/issues/64)
-   Add Sonar configuration to analyze and publish generated project for backend [issue #87](https://github.com/jhipster/generator-jhipster-nodejs/issues/87)
-   Update with last jhipster version and add blueprint as devDependency project [issue #111](https://github.com/jhipster/generator-jhipster-nodejs/issues/111)

I have resolved some bugs, introduced docker images, sonar quality, more generation test scenarios, and more stability.

**Comment by amanganiello90** [comment]
I'm very happy to announce the first published [1.0.0 blueprint version](https://www.npmjs.com/package/generator-jhipster-nodejs/v/1.0.0)!
@jhipster/developers, @feitian124, @ajoysinhactc, @Zahma, @MathieuAA, @walshe-boylesoftware, @kosnkow, @ItsInsajd, @robconnell9, @jhipster/hipsters, @danielpetisme  and @hadirsa

**Comment by MathieuAA** [comment]
Ah ! Excellent news, great work!

**Comment by amanganiello90** [comment]
> 
> 
> Ah ! Excellent news, great work!

Thanks, sweet!

**Comment by jdubois** [comment]
Awesome!!! Let me tweet this right away with the official JHipster account

**Comment by pascalgrimaud** [comment]
good job @amanganiello90

**Comment by Zahma** [comment]
Excellent job, lets keep it up

**Comment by FanchGadjo** [comment]
Congratulations ! 🎉
