### ISSUE TITLE
Installation on Windows can not copy file with prefix "."

### ISSUE THREAD

**Issue by Aragonbn90** [jhipster/generator-jhipster-nodejs#118]
**Describe the bug**
1. On windows, install with: npm install -g generator-jhipster-nodejs success
2. Generate new monolithic app: jhipster --blueprints nodejs
3. See error: 
4. See error:
Error: Copying template server/.server.eslintrc.json.ejs failed. [Error: ENOENT: no such file or directory, open 'C:\ProgramData\nvm\v12.16.1\node_modules\generator-jhipster-nodejs\generators\server\templates\server\.server.eslintrc.json.ejs']

-   OS: Windows 10
-   npm version 6.13.4

I temp fixed this error by directly copy all file with prefix "." from github to local

**Comment by amanganiello90** [comment]
Thanks for the issue. Maybe during the npm publish it ignored some files. So I will check it.

**Comment by amanganiello90** [comment]
You are right!! thank you very much for the feedback!! all the dot templates are ignored, so I will fix it releasing a new 1.0.1 version.

**Comment by amanganiello90** [comment]
Now you can check with the last https://www.npmjs.com/package/generator-jhipster-nodejs/v/1.0.1 version. Thanks
