### ISSUE TITLE
Support i18n for backend and frontend

### ISSUE THREAD

**Issue by Aragonbn90** [jhipster/generator-jhipster-nodejs#119]
**Is your feature request related to a problem? Please describe.**
Have not supported internationalization.

**Describe the solution you'd like**
Frontend: same solution with generator-jhipster
Backend: use https://www.npmjs.com/package/nestjs-i18n/v/4.1.3, that comforts with current version of nestjs

**Additional context**
Please give me some advice. I want to contribute this feature. Thanks.

**Comment by amanganiello90** [comment]
Hi @Aragonbn90, thanks for the interest!
Before we have to enable i18n for Angular /react client (only for the home page I have customize that).
The last has already open issue #45 
So do you refer to the backend? It has only rest api, what would you like to internationalize?

**Comment by Aragonbn90** [comment]
I will try with #45 and #59 first, then with frontend support, and last with backend.
I'm a Java and Node.js developer. I'm going to use this generator more times. So I want to complete it, to have full feature like generator-jhipster.

**Comment by amanganiello90** [comment]
Sweet! you are welcome!
So.. have you experience with jhipster blueprints?

**Comment by Aragonbn90** [comment]
I used jhipster from Sep 2019. It's so amazing.
I will try to learn jhipster blueprints.
Many thanks for your guidelines.

**Comment by amanganiello90** [comment]
Closed with #160
