### ISSUE TITLE
Unauthorized error in jwt authentication when run client and server separately

### ISSUE THREAD

**Issue by yotamshapira** [jhipster/generator-jhipster-nodejs#124]
**Describe the bug**
When running the client separately from the server, as described in the README.md file, I can't log in

**To Reproduce**

1. On one terminal, run:
`cd server && npm start`
2. On a second terminal, run:
`npm start`
3. A browser window opens on `http://localhost:9000/`
4. Sign in using any credential (e.g. user `admin`, password: `admin`) - log in fails

**Expected behavior**
User should be logged in.
Note that if I build the client and then run the server, using `http://localhost:8081/`, I can log in (but then I do not get the auto-refresh experience).

**Screenshots**
![image](https://user-images.githubusercontent.com/2280715/79271757-019f2080-7ea9-11ea-9749-c7b696583b1a.png)

**Desktop (please complete the following information):**

-   OS: MacOS 10.15.1
-   Browser chrome
-   Version 80

**Additional context**
* My configuration:
```? What is the base name of your application? <my app's name>
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *production* database would you like to use? MySQL or MariaDB
? Which *Framework* would you like to use for the client? Angular
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to install other generators from the JHipster Marketplace? No
```
* Same behavior on https://github.com/jhipster/jhipster-sample-app-nodejs/tree/v1.0.1

**Comment by amanganiello90** [comment]
Hi, thanks for the feedback.
So, when you run separately server and client in two command lines, you have to specify the backend endpoint in the angular/react client.
Instead, when you build client and run the nestjs app, it will copy the build under express, and run backend and client as a full app (as it were an only server).

For backend refresh you have to run **npm run start:dev** task under server folder.

**Comment by yotamshapira** [comment]
> Hi, thanks for the feedback.
> So, when you run separately server and client in two command lines, you have to specify the backend endpoint in the angular/react client.
> Instead, when you build client and run the nestjs app, it will copy the build under express, and run backend and client as a full app (as it were an only server).
> 
> This is a client jhipster configuration: https://github.com/jhipster/jhipster-sample-app-nodejs/blob/a9dd1dd36efb6a082ebc1813120340d47fb78dca/webpack/webpack.common.js#L72
> 
> For backend refresh you have to run **npm run start:dev** task under server folder.

I tried modifying the SERVER_API_URL to ```SERVER_API_URL: `'http://localhost:8081/'` ```, but that had the same effect as leaving it empty (as generated).
I don't think this is the issue since the first call, a POST request to `http://localhost:8081/api/authenticate` is successful (see screenshot in the issue description).

**Comment by yotamshapira** [comment]
By the way, you can see this behaviour in the sample app - https://github.com/jhipster/jhipster-sample-app-nodejs

**Comment by amanganiello90** [comment]
Yes, the first request is ok because it retrieves the jwt token (that api does not have security). But the following api (account), is protected and it return unauthorized response (401). The workflow is the same if you run the full stack app, maybe there is a problem for CORS in case that you have two separately app (a client that calls an external server).

**Comment by amanganiello90** [comment]
$100 bug bounty claim: https://opencollective.com/generator-jhipster/expenses/24651
