### ISSUE TITLE
Entity not saved with relationship for many-to-one

### ISSUE THREAD

**Issue by yotamshapira** [jhipster/generator-jhipster-nodejs#125]
**Describe the bug**

**To Reproduce**

1. Clone the sample application - https://github.com/jhipster/jhipster-sample-app-nodejs:
`git clone git@github.com:jhipster/jhipster-sample-app-nodejs.git`
2. Modify `server/package.json` as described in #120 
3. Install dependencies in client & server
`npm install`
`cd server && npm install`
4. Create the following entities in .jhipster (they were originally generated, but I show them here as files to make reproduction easier):

`.jhipster/One.json`:
```
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20200414210240",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceImpl",
    "entityTableName": "one",
    "databaseType": "sql",
    "readOnly": false,
    "jpaMetamodelFiltering": false,
    "pagination": "pagination"
}
```

`.jhipster/Many.json`:
```
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [
        {
            "relationshipName": "one",
            "otherEntityName": "one",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20200414210511",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceImpl",
    "entityTableName": "book",
    "databaseType": "sql",
    "readOnly": false,
    "jpaMetamodelFiltering": false,
    "pagination": "pagination"
}
```

5. (Re)generate the entities:
`jhipster entity one --blueprints nodejs` and select `Yes, re generate the entity` and override all files
`jhipster entity many --blueprints nodejs` and select `Yes, re generate the entity` and override all files

6. Run the application: `npm run start:app`
7. Go to `http://localhost:8081/` and log in as `admin`
8. Go to Entities->One and create an instance
9. Go to Entities->Many and create an instance, make sure you link the new instance to the `One` entity you have created in the previous step (see screenshot 1).
10. You can now see that the `Many` entity that was created has no link to the `One` Entity (see screenshot 2). Note that the response from the server has no mention of the `One` relationship (see screenshot 3)

**Expected behavior**
Entities should be linked and that should be reflected in the UI

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/2280715/79321353-df8eb800-7f13-11ea-9575-88b60a868572.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/2280715/79321485-1b298200-7f14-11ea-9957-b8f75565daf8.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/2280715/79321595-46ac6c80-7f14-11ea-86fd-2fb4ed29b140.png)

**Desktop (please complete the following information):**

-   OS: MacOS 10.15.1
-   Browser chrome
-   Version 80

**Additional context**
N/A

**Comment by amanganiello90** [comment]
Thanks for the feedback. But I don't understand very well.. Could you please open the view tab of entity with Many title and see if the mask contains One entity?

**Comment by yotamshapira** [comment]
No, its not there. The backend does not return the author field at all
![image](https://user-images.githubusercontent.com/2280715/79329271-2b475e80-7f20-11ea-8d74-952e01e62d22.png)

![image](https://user-images.githubusercontent.com/2280715/79329343-4d40e100-7f20-11ea-8d19-34715b4ea14f.png)

**Comment by amanganiello90** [comment]
In your case it is missed the name field under one entity. Could you import this jdl and test the many-to-one relationship? (if there is the same issue): https://github.com/jhipster/generator-jhipster-nodejs/blob/master/test-integration/samples/microservice-oauth2-sql-jdl/microservice-oauth2-sql-jdl.jdl

**Comment by yotamshapira** [comment]
Same thing happens, the relation is not returned to the server or shown in the UI (it WAS sent to the server in the POST request creating the entity, same as in my example).

![image](https://user-images.githubusercontent.com/2280715/79330863-e7a22400-7f22-11ea-98ae-6f1125c754b1.png)

![image](https://user-images.githubusercontent.com/2280715/79330887-f25cb900-7f22-11ea-848b-841e841628d7.png)

**Comment by amanganiello90** [comment]
ok, I investigate on it, maybe there is an error on annotation mapped in the entity.ts

**Comment by amanganiello90** [comment]
I fix with https://github.com/jhipster/generator-jhipster-nodejs/commit/d6354b99fcb9a4ca76c39947fa7f8ff8af7ebe84 .
Try it. Thanks

**Comment by amanganiello90** [comment]
Check on new release: https://www.npmjs.com/package/generator-jhipster-nodejs/v/1.0.2 .
If there are another problems, fell free to open new issues. Thanks.
