### ISSUE TITLE
Blob types not saved

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#129]
Blob images file are not saved in sqlite.

**Comment by amanganiello90** [comment]
Today ImageBlob jdl type instead is saved

**Comment by mraible** [comment]
@amanganiello90 Is this available in a released version of this blueprint?

**Comment by amanganiello90** [comment]
I don't know if the last release is ok, I have tested the latest commits

**Comment by amanganiello90** [comment]
$200 bug bounty claim: https://opencollective.com/generator-jhipster/expenses/24650
