### ISSUE TITLE
Task: entity-server generator and TypeORM mappings

### ISSUE THREAD

**Issue by ivangsa** [jhipster/generator-jhipster-nodejs#13]
Hi

I would like to contribute code for TypeORM mappings for the server-entity generator. I will be starting right now unless you decide a different technology is a better fit.

**Comment by amanganiello90** [comment]
Hi @ivangsa, thank you very much for your helping! I'm always entusiastic with new contributors, and I love to answer very quickly to coordinate this generator..so let's grew up this project!...
Well, as I have said to @hadirsa on [gitter](https://gitter.im/generator-jhipster-nodejs/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge),  we have before to "clean" the pom.xml generated. Please, refer to nest.js app example indicated on the chat, and follow that typeorm, if you prefer for the entity subgenerator. For any questions, feedback, improvements, feel easy to ask me. Thanks.

**Comment by amanganiello90** [comment]
closed with #21
