### ISSUE TITLE
Navigating to admin screens results in 404 errors

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-nodejs#133]
**Describe the bug**

Create a React + OAuth 2.0 app, start it, then navigate to the **Administration** screens. The first one results in a 404 error, as do the rest of them.

<img width="1438" alt="Screen Shot 2020-05-04 at 8 56 38 PM" src="https://user-images.githubusercontent.com/17892/81031574-ec833500-8e49-11ea-91b2-e61609a5ede9.png">

**Comment by amanganiello90** [comment]
Hi Matt,
thanks for the feedback! Now the nodejs server does not manage administration part (JVM Metrics is not a nodejs feature).

**Comment by mraible** [comment]
In that case, it might make sense to override the navbar template and remove the Administration menu.

**Comment by amanganiello90** [comment]
Thanks, I fix it.

**Comment by amanganiello90** [comment]
I close it because I have list all the changes in #136
