### ISSUE TITLE
Enhancement suggestions list tasks for 1.1.0 version

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#136]
For @mraible tests, we list the enhancement tasks:

- #131 include lint:fix in npm test task
- #132 add space in react home page for signin line
- #133 Delete admin UI panel
- #134 update README.md and message of the start script to run
- #138 Allows postgresql database in jdl

So in this issue will be resolved all tasks.

**Comment by mraible** [comment]
@amanganiello90 If you'd like to assign bug bounties to issues in this project, please create a proxy ticket in `generator-jhipster` and I can assign $$ to it. [Here's an example](https://github.com/jhipster/generator-jhipster/issues/11690) for a Vue.js enhancement.

**Comment by amanganiello90** [comment]
Ok thanks, I would like to propose @Aragonbn90 , if he is interested :)

**Comment by Aragonbn90** [comment]
Yeh, I'm always interested in this project :D

**Comment by amanganiello90** [comment]
Well, I assign you this issue, and Matt will give you a bounty to resolve ;)

**Comment by amanganiello90** [comment]
Wonderful, @Aragonbn90 you can start when you want. Let you fell free to ask me more details ;)
