### ISSUE TITLE
sqlite doesn't support enum

### ISSUE THREAD

**Issue by amirmehdi** [jhipster/generator-jhipster-nodejs#139]
I used this jdl to import in a monolithic project.
https://github.com/jhipster/jdl-samples/blob/master/online-shop.jh

two issues occurred:
1. wrong import in the category in category-model and category-entity . that's not important
2. error in npm start occurred: 
Data type "enum" in category is not supported by "sqlite" database.

I solved this issue in development mode by this:
https://github.com/typeorm/typeorm/issues/1414

I use 'simple-enum' in type field for @column

**Comment by amanganiello90** [comment]
You are the best!! Could you contribute with a Pull Request? it should be very nice :)

**Comment by amanganiello90** [comment]
The import error is due to a recursive relationship:

```
relationship ManyToOne {
	Category{parent} to Category
}
```

**Comment by amanganiello90** [comment]
I have just fixed the recursive import and adding new simple-enum type (merged by PR). Thanks.
