### ISSUE TITLE
Vue support. 

### ISSUE THREAD

**Issue by olegruchovets** [jhipster/generator-jhipster-nodejs#141]
Hi Guys. 
   Do you support vuejs?

**Comment by amanganiello90** [comment]
Hi! This is a blueprint for the server side, not ovverride client generation.
For VueJS there is an external module: https://github.com/jhipster/jhipster-vuejs
Besides, in the nest jhipster 7.x release, it will be included as a client option: https://github.com/jhipster/generator-jhipster/issues/10575
