### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by MattLish** [jhipster/generator-jhipster-nodejs#148]
## Overview of the issue

In this issue you mention that MongoDB doesn't work. 
https://github.com/jhipster/generator-jhipster-nodejs/issues/51

Is there anything on the roadmap to have this added back in?
What doesn't work about it?
If I was to add mongoDB back into the Type ORM settings, what production issues am I likely to face?

## Reproduce the error
N/A

## Related issues
N/A

## Link to PR (if any)
N/A

## JHipster Version(s)
6.8.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by amanganiello90** [comment]
Hi @MattLish, thanks for the interest! Now there is not supported mongodb, because in dev mode the application starts with sqlite. So we need to keep that in dev, and enable mongodb in prod running.
#73

**Comment by MattLish** [comment]
@amanganiello90 I see. I missed that issue. Thanks for the reply. Feel free to close this issue if you feel it adds no value.

**Comment by mraible** [comment]
@amanganiello90 The main JHipster generator allows you to use MongoDB in development via Docker Compose. Why can't this blueprint do the same?

**Comment by amanganiello90** [comment]
Hi @mraible, the last idea is to use only a mongodb for production chooise, but the default db for development is always sqlite. Your idea instead is to use mongodb for dev and production (that could be another solution).

**Comment by MattLish** [comment]
@amanganiello90 I feel like that would be an acceptable solution to use Mongo in dev/prod. Most people that use Mongo in production are likely to want to test using Mongo in dev mode.

**Comment by amanganiello90** [comment]
Ok, we can work on that configuration, a mongodb for dev/prod environment
