### ISSUE TITLE
jest-diff error running "npm run webpack:prod"

### ISSUE THREAD

**Issue by ecirilo** [jhipster/generator-jhipster-nodejs#149]
**Describe the bug**
Doing an npm run webpack:prod in server folder of a generated app shows the import errors:

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts(10,13)
      TS1005: '=' expected.

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts(10,34)
      TS1005: ';' expected.

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts(11,1)
      TS1128: Declaration or statement expected.

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts(11,13)
      TS1005: ';' expected.

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/index.d.ts(11,52)
      TS1005: ';' expected.

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/diffLines.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/diffLines.d.ts(8,13)
      TS1005: '=' expected.

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/diffLines.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/diffLines.d.ts(8,34)
      TS1005: ';' expected.

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/printDiffs.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/printDiffs.d.ts(8,13)
      TS1005: '=' expected.

ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/printDiffs.d.ts
[tsl] ERROR in /Users/elder/Programming/oomenu/backoffice/server/node_modules/jest-diff/build/printDiffs.d.ts(8,57)
      TS1005: ';' expected.

**To Reproduce**

1. Go to server folder
2. Run npm run webpack:prod

**Expected behavior**
Have the production bundle built with webpack

**Desktop (please complete the following information):**

-   OS: macOs 10.15.4

**Additional context**
jhipster-nodejs v1.0.2

**Comment by amanganiello90** [comment]
Hi!! Thanks for the interest!
This is a new bug of jest: https://github.com/facebook/jest/issues/9714#issuecomment-604678837
I have just fixed that with the following steps:
- Update in your server package.json the jest and @types/jest to 25.2.3 version
- Add in your webpack.server.prod.config.ts the following section:

```
  externals: {
        '@nestjs/microservices': 'nestjs/microservices',
        'cache-manager': 'cache-manager',
        'fastify-swagger': 'fastify-swagger',
	'aws-sdk': 'aws-sdk',
    },
```

These steps resolve that. I'm starting a branch on the generator.
