### ISSUE TITLE
add NestJS basic templates

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#15]
@hadirsa, I can't assign you this issue because you aren't in the jhipster group.
 Don't worry, you will be soon :) . So I have moved the activity discussed in [gitter](https://gitter.im/generator-jhipster-nodejs/community) from the kanban board and tag you. 
For every question feel free to ask me. Thank you very much for your contribution!

**Comment by hadirsa** [comment]
@amanganiello90, I start to do this task. thanks.

**Comment by amanganiello90** [comment]
@hadirsa, I have just modified and implemented an app for us [example app](https://github.com/amanganiello90/nestjs-sequelize-typescript/tree/jhipster-dts).
In this project, that it had jwt and nestJS swagger integration, I have added the new DTS and replaced sequelize orm with TypeORM including sqlite instead of Postgres. But now the jwt authentication doesn't work. If you want to fix it, you are welcome, otherwise now it's more important a session authentication and manage the build and running in jhipster. Thanks

**Comment by hadirsa** [comment]
@amanganiello90, I'll check it and inform you about the changes, I have tried to generate server part with our own structure. it persists on creating with maven structure.  Do I need to change `this.SERVER_MAIN_SRC_DIR = constants.SERVER_MAIN_SRC_DIR;` or something?

**Comment by hadirsa** [comment]
@amanganiello90 , `jwt authentication doesn't work.`, I have checked. it's working, I have registered a user, i have created a post and get all posts.
could please tell more about the error? 
response for my login for new use in postman :

```
{
    "id": "d3c168ba-f0fc-467b-94a1-38008a4d2989",
    "email": "admin@aa.com",
    "firstName": "hadi",
    "lastName": "raso",
    "gender": null,
    "birthday": null,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFhLmNvbSIsImlhdCI6MTU2NTk3Nzg0NX0.A_eU2BSk2U4Q1_gguxeSWoKo_wjZiPMcE7c4OJOLM_A"
}
```

**Comment by amanganiello90** [comment]
@hadirsa, for the server directory we have not decided yet. Instead, for the example project, I had created a user using the swagger ui server on **localhost:3000/docs** using your request. Then I have added the previous token received in the header request (bearer <token>) calling the users get (that is protected), as explained in: https://docs.nestjs.com/recipes/swagger#authentication

**Comment by amanganiello90** [comment]
Hi @hadirsa ,
@ivangsa  with #21 has resolved the issue. Thanks a lot.

**Comment by hadirsa** [comment]
Hi @amanganiello90, good to hear, thanks @ivangsa, I was in the middle of the task. so I can switch to another one.
