### ISSUE TITLE
double stitch port on app.yml 

### ISSUE THREAD

**Issue by ssanusi** [jhipster/generator-jhipster-nodejs#157]
**Describe the bug**
After generating the nhipster app i tried to run it with docker, however i get the error 
```
ERROR: The Compose file './src/main/docker/app.yml' is invalid because: services.ecommerce-app.ports is invalid: Invalid port "{'8081:8081': None}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol] services.ecommerce-app.ports contains an invalid type, it should be a string, or a number
```
so i have to remove the semi-column on the ports from ``` /src/main/docker/app.yml ``` 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by amanganiello90** [comment]
Thanks for the feedback, you are welcome!
