### ISSUE TITLE
Vue.js support from 7.x jhipster upgrade

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#158]
From the 7.0 jhipster version (now the latest is the 6.10.1), it will be integrated the vue.js client.
So it is advisable to upgrade jhipster in order to integrate that feature and resolve #147 bug.
Besides, the vue.js client should be tested (entity generation, runtime, security with jwt and oidc) and it should be customized the home page for nhipster.
What do you think @mraible? Should we add a bug bounty?

**Comment by mraible** [comment]
@amanganiello90 I added a $200 bounty.

**Comment by amanganiello90** [comment]
Great! As soon as the 7.0 jhipster version will be released, we could start this important feature.

**Comment by amanganiello90** [comment]
$200 bug bounty claim: https://opencollective.com/generator-jhipster/expenses/37428
