### ISSUE TITLE
New pom.xml template without unuseful dependencies

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#16]
@hadirsa, I can't assign you this issue because you aren't in the jhipster group.
 Don't worry, you will be soon :) . So I have moved the activity discussed in [gitter](https://gitter.im/generator-jhipster-nodejs/community) from the kanban board and tag you. 
For every question feel free to ask me. Thank you very much for your contribution!

**Comment by hadirsa** [comment]
Great. Thanks, @amanganiello90. :)

**Comment by amanganiello90** [comment]
Task completed. Thanks
