### ISSUE TITLE
Unexpected authorized access in security jwt with wrong username but correct password

### ISSUE THREAD

**Issue by A-5ingh** [jhipster/generator-jhipster-nodejs#164]
**Describe the bug**
After generating default Monolithic application using nhipster with frontend as either angular or react. We can login into application by using credentials without entering any username:
1. Username - (any string or blank), password - admin
2. Username - (any string or blank), password - user

**To Reproduce**

1. Generate monolithic application using any frontend, install dependencies and run the application.
2. Go to Account menu
3. Click on Sign In
4. Enter invalid username but correct password
5. User gets logged in

**Expected behavior**
User should not be able to login into the application with invalid username and correct password.

**Screenshots**
![MainPage](https://user-images.githubusercontent.com/32884734/91800079-fb39f700-ec45-11ea-93d7-9eca980d6141.PNG)
![SuccessfullLogin](https://user-images.githubusercontent.com/32884734/91800080-fc6b2400-ec45-11ea-9fac-48ede6b03acc.PNG)

**Desktop (please complete the following information):**

-   OS: Windows Server 2012 R2
-   Browser: Chrome
-   Version: 84.0.4147.135

**Additional context**
Same issue can be seen in swagger api, we can authenticate user by providing incorrect username and correct password.

**Comment by amanganiello90** [comment]
Hi @A-5ingh , thanks for the interest!
have you ever tried with username "admin" and password "admin"?

**Comment by amanganiello90** [comment]
Thanks! I have found the bug and fix that. You are welcome!

**Comment by A-5ingh** [comment]
> Thanks! I have found the bug and fixed that. You are welcome!

Thank you for the quick fix. Yes, I was able to login with any string as username (even empty, that will be another client validation failure bug). Only the password had to be correct (means of any account like admin/user etc).

**Comment by amanganiello90** [comment]
Yeah @A-5ingh , it's very simple, the commit has the issue number as message 👍
