### ISSUE TITLE
Administrator module is not configured in nodejs like other jhipster project 

### ISSUE THREAD

**Issue by Shahid2130** [jhipster/generator-jhipster-nodejs#165]
## JHipster Version(s)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by amanganiello90** [comment]
Hi! thanks for the interest!
So the admin panel is been deleted as reportend by [this issue](https://github.com/jhipster/generator-jhipster-nodejs/issues/133).
The reason is that nodejs has not a VM to monitoring and there is supported a management for nodejs yet.
