### ISSUE TITLE
Support the account management with user registration, delete, creation and changes password with settings

### ISSUE THREAD

**Issue by solidtechvn** [jhipster/generator-jhipster-nodejs#166]
**Describe the bug**
Project generated return 401 status when register new user
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
My .yo-rc-json file:
{
  "generator-jhipster": {
    "SolidtechVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "technews",
    "packageName": "com.jhipster.node",
    "packageFolder": "com/jhipster/node",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "sqlite",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "skipClient": true,
    "creationTimestamp": 1600238386556,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "1.2.0"
      }
    ],
    "enableTranslation": false,
    "blueprints": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "1.2.0"
      }
    ]
  }
}

**Comment by amanganiello90** [comment]
HI! thanks for the interest!
Could you please add your .yo-rc.json file?

**Comment by solidtechvn** [comment]
@amanganiello90 Added

**Comment by amanganiello90** [comment]
Thanks, I checked your problem. Now the framework does not supports the registration of new users. So your issue is due that the user is not created. I will add it in the backlog.

**Comment by amanganiello90** [comment]
Caused by #101, we need to perform user administration (create and delete user, change password, change settings with email). In this way the standard protractor e2e tests could be run (especially for react that have more tests then angular).
