### ISSUE TITLE
TS2304: Cannot find name 'Cheerio' in React app

### ISSUE THREAD

**Issue by skmaingi** [jhipster/generator-jhipster-nodejs#167]
**Describe the bug**

'Cheerio' not found in node module script @types/enzyme/index.d.ts

**To Reproduce**
Steps to reproduce:

1) Install blueprint
`npm install -g generator-jhipster-nodejs`

2) Generate application
`jhipster --blueprints nodejs`

3) Install modules
`npm install`

4) Run/build application
`npm start` or
`npm run start:app` or
`npm run webpack:prod`

**Expected behavior**
Run / build application without error.

**Screenshots**
![Screenshot from 2020-09-24 17-21-33](https://user-images.githubusercontent.com/961603/94176847-5b1c6a00-fea1-11ea-94d4-35202daa0f99.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu Xenial Xerus
-   Browser Chrome
-   Version 85

**Additional context**

**Comment by amanganiello90** [comment]
Hi @skmaingi , thanks for the interest! 
In the your steps I don't read the npm install under server folder.
Please consider the (README..md)[https://github.com/jhipster/jhipster-sample-app-nodejs/blob/master/README.md#development].

However, I have an issue on the backlog to execute the install after generation #161

**Comment by skmaingi** [comment]
Hi @amanganiello90 , 
Thank you for reply. This issue is affecting Frontend node modules

**Comment by ruddell** [comment]
This is related to an issue in the main generator, https://github.com/jhipster/generator-jhipster/issues/12593

**Comment by amanganiello90** [comment]
Thanks to @skmaingi and @ruddell, but after updating the dependency we have another error:

```
ERROR in /home/runner/work/generator-jhipster-nodejs/generator-jhipster-nodejs/test-integration/samples/monolith-react-jwt-jdl/src/test/javascript/spec/app/shared/error/error-boundary-route.spec.tsx(29,54):
TS2339: Property 'render' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.
```
https://github.com/jhipster/generator-jhipster-nodejs/runs/1177065705#step:13:230

**Comment by solidtechvn** [comment]
I resolve this issue by add
"@types/cheerio": "^0.22.11"
 "@types/enzyme": "3.9.1",
like if it help you gúy

**Comment by amanganiello90** [comment]
@solidtechvn thanks, it works!
