### ISSUE TITLE
Polyfilling node core modules when upgrade to Jhipster 6.10

### ISSUE THREAD

**Issue by sabeurios** [jhipster/generator-jhipster-nodejs#178]
I have an existing project generated with jhipster 5.7 so I upgraded it to 6.10 and I transferred the existing files to the new directory and suddenly I had this polyfilling problem
<img width="743" alt="Screenshot 2020-10-29 at 09 19 28" src="https://user-images.githubusercontent.com/57177536/97696797-5f423580-1aa6-11eb-8602-8532721a679d.png">

I opened a subject in the webpack form but they directed me here

**Comment by amanganiello90** [comment]
Hi @sabeurios, thanks for the issue! But... it is not related to the NHipster :-) ...
The reasons are:

1. NHipster is not born with JHipster 5.7 but with [JHipster 6.3.0](https://github.com/jhipster/generator-jhipster-nodejs/blob/15fb40d7eea2ebc7308b81cf39ff5d707ef0145e/package.json#L35)
2. NHipster is the official JHipster blueprint that replaces java backend with nodejs backend. Your error is related to the frontend client and not to nodejs backend
3. For the last two points, it seems that you have generated an application with [JHipster](https://github.com/jhipster/generator-jhipster)  and not with **NHipster**

Therefore, you should open a issue on the related [jhipster repo issues](https://github.com/jhipster/generator-jhipster/issues) and expose your reason. Thanks
