### ISSUE TITLE
Add validation in dto nestjs controllers

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#182]
Add support to validate dto's fields: https://docs.nestjs.com/techniques/validation

**Comment by stefandekeijzer** [comment]
Do you have a timeline when this will be available?

**Comment by amanganiello90** [comment]
I don't know at the moment. I' m working on #101 and #106, and it is a lot of stuff.

**Comment by amanganiello90** [comment]
The #181 is been completed, so I start this feature on [feature/dto-validation-issue182 branch](https://github.com/jhipster/generator-jhipster-nodejs/tree/feature/dto-validation-issue182)
