### ISSUE TITLE
Bug: The module at index [3] of the AppModule "imports" array is undefined

### ISSUE THREAD

**Issue by JavierFuentes** [jhipster/generator-jhipster-nodejs#193]
**Describe the bug**
I've imported the default sample from https://start.jhipster.tech/jdl-studio/ in a new NHipster project with default values for everything and PosgreSQL as production database.

When I execute `cd server && npm start` command, I've got this error:

```bash
[Nest] 13352   - 2020-12-20 17:38:54   [Config] Actual process.env.NODE_ENV value: dev
[Nest] 13352   - 2020-12-20 17:38:54   [Config] Standard allowed values are: dev, test or prod
[Nest] 13352   - 2020-12-20 17:40:45   [NestFactory] Starting Nest application... +110169ms
[Nest] 13352   - 2020-12-20 17:40:45   [ExceptionHandler] Nest cannot create the AppModule instance.
The module at index [3] of the AppModule "imports" array is undefined.

Potential causes:
- A circular dependency between modules. Use forwardRef() to avoid it. Read more: https://docs.nestjs.com/fundamentals/circular-dependency
- The module at index [3] is of type "undefined". Check your import statements and the type of the module.

Scope [] +38ms
Error: Nest cannot create the AppModule instance.
The module at index [3] of the AppModule "imports" array is undefined.

Potential causes:
- A circular dependency between modules. Use forwardRef() to avoid it. Read more: https://docs.nestjs.com/fundamentals/circular-dependency
- The module at index [3] is of type "undefined". Check your import statements and the type of the module.
```

I've noticed that in `server/src/app.module.ts` file I've got this bug with an additional comma after _AuthModule_:

```ts
@Module({
  imports: [
    TypeOrmModule.forRoot(ormconfig),
    ServeStaticModule.forRoot({
      rootPath: config.getClientPath()
    }),
    AuthModule,
    ,
    RegionModule,
   ...
  ],
  controllers: [ ],
  providers: [ ]
})
export class AppModule {}
``` 

I've deleted this comma, and try to compile again with `npm start` but then new Errors throws related to data-types conversions for SQLITE3 database...

```bash
DataType NotSupportedError: Datatype "long" is not supported by "sqlite" database.

DataType NotSupportedError: Datatype "timestamp" is not supported by "sqlite" database.
```

To solve that 2 new issues, I've edited `jhipster-jdl.jdl` file and replace **`Long` with `Integer`** and **`Instant` with `LocalDate`**

After that, project runs OK.

**To Reproduce**

1. Create a new App with `nhipster` command and select PosgreSQL as production database
2. Download default-sample from https://start.jhipster.tech/jdl-studio/ to your project folder
3. Import with `nhipster import-jdl jhipster-jdl.jdl` command
4. Execute  `cd server && npm start` in a terminal window
5. Wait for a while and see the 1st Error described before
6. Delete additional comma and try again...
7. Wait for a while and see the 2nd Error described before

**Expected behavior**
I understand that additional comma in `server/src/app.module.ts` file could be a Bug and I would like to be solved.

I understand that data-type conversions error is a responsibility of TypeORM and I don't know if you can do anything to avoid them.

**Screenshots**
![image](https://user-images.githubusercontent.com/5801847/102719518-e9608a80-42ee-11eb-8f94-641e3e00b217.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser: Edge Chromium
-   Version: 87.0.664.66 

**NHipster configuration**

```bash
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
prueba-nhipster@0.0.1-SNAPSHOT C:\IdeaProjects\prueba_nhipster
+-- generator-jhipster@6.8.0
`-- generator-jhipster-nodejs@1.4.0
  `-- generator-jhipster@6.8.0  deduped

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "prueba_nhipster",
    "packageName": "com.jhipster.node",
    "packageFolder": "com/jhipster/node",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "sqlite",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "pulse",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1608467182789,
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "1.4.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": ["es", "en"],
    "blueprints": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "1.4.0"
      }
    ]
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Region {
  regionName String
}
entity Country {
  countryName String
}
/**
 * not an ignored comment
 */
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Department {
  departmentName String required
}
/**
 * Task entity.\n@author The JHipster team.
 */
entity Task {
  title String,
  description String
}
/**
 * The Employee entity.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate Instant,
  salary Long,
  commissionPct Long
}
entity Job {
  jobTitle String,
  minSalary Long,
  maxSalary Long
}
entity JobHistory {
  startDate Instant,
  endDate Instant,
  language Language
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region,
  Location{country} to Country,
  Department{location} to Location,
  JobHistory{job} to Job,
  JobHistory{department} to Department,
  JobHistory{employee} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to
  /**
   * Another side of the same relationship
   */
  Employee{department},
  Employee{job} to Job{employee}
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

service Region, Country, Location, Department, Task, JobHistory with serviceImpl
paginate Employee, JobHistory with infinite-scroll
paginate Job with pagination

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.17.0.windows.1

node: v12.20.0

npm: 6.14.8

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!
```

**Comment by amanganiello90** [comment]
Hi @JavierFuentes,
thanks for the issue!
So I have tried to replicated it.

I first generated the application according your yo-rc.json, and after run import-jdl with your model (always with --skipInstall).
Finally my app.module is:

```
@Module({
  imports: [
    TypeOrmModule.forRoot(ormconfig),
    ServeStaticModule.forRoot({
      rootPath: config.getClientPath()
    }),
    AuthModule,
    RegionModule,
    CountryModule,
    LocationModule,
    DepartmentModule,
    TaskModule,
    EmployeeModule,
    JobModule,
    JobHistoryModule
    // jhipster-needle-add-entity-module-to-main - JHipster will add entity modules here, do not remove
  ],
  controllers: [
    // jhipster-needle-add-controller-module-to-main - JHipster will add controller modules here, do not remove
  ],
  providers: [
    // jhipster-needle-add-service-module-to-main - JHipster will add service modules here, do not remove
  ]
})
export class AppModule {}
```

**Comment by JavierFuentes** [comment]
Hi @amanganiello90,
Hmmm... it's strange... I tried for 3 times with clean and fresh projects with the same Issue until I discovered where was the problem...

It's true I executed yesterday _JHipster Information Sub-Generator_ after I'd solved all the problems... I don't know if it was an error or not...

Have you tested to download .JDL file from https://start.jhipster.tech/jdl-studio too?

**Comment by amanganiello90** [comment]
If I click on https://start.jhipster.tech/jdl-studio I see my jdl and not yours, because it enters with own account :)... So I have used the jdl that you have linked in the issue.

**Comment by JavierFuentes** [comment]
Ok, can you access in a private tab o with other browser yo see default-sample this Page shows to everybody without an account like me?

**Comment by amanganiello90** [comment]
The jdl-studio save jdl model diagram per account, so if you click on the link you see your model while in my case I can view my model. However I have used the model that you have linked in the description of the issue:

```
entity Region {
  regionName String
}
entity Country {
  countryName String
}
/**
 * not an ignored comment
 */
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Department {
  departmentName String required
}
/**
 * Task entity.\n@author The JHipster team.
 */
entity Task {
  title String,
  description String
}
/**
 * The Employee entity.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate Instant,
  salary Long,
  commissionPct Long
}
entity Job {
  jobTitle String,
  minSalary Long,
  maxSalary Long
}
entity JobHistory {
  startDate Instant,
  endDate Instant,
  language Language
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region,
  Location{country} to Country,
  Department{location} to Location,
  JobHistory{job} to Job,
  JobHistory{department} to Department,
  JobHistory{employee} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to
  /**
   * Another side of the same relationship
   */
  Employee{department},
  Employee{job} to Job{employee}
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

service Region, Country, Location, Department, Task, JobHistory with serviceImpl
paginate Employee, JobHistory with infinite-scroll
paginate Job with pagination
```

**Comment by amanganiello90** [comment]
I close this issue because it does not seems a bug, as explained.

**Comment by ifelse-codes** [comment]
> executed
@JavierFuentes
I have a fresh install of jhipster and nhipster , I am running it to the same issue you reported here ..

can you please help me with the steps to solve this

**Comment by JavierFuentes** [comment]
Hi @ifelse-codes,
check if you have an an additional comma (added automatically) after **AuthModule** in `server/src/app.module.ts` file.

See my [screenshot above](https://user-images.githubusercontent.com/5801847/102719518-e9608a80-42ee-11eb-8f94-641e3e00b217.png):

**Comment by ifelse-codes** [comment]
> Hi @ifelse-codes,
> check if you have an an additional comma (added automatically) after **AuthModule** in `server/src/app.module.ts` file.
> 
> See my [screenshot above](https://user-images.githubusercontent.com/5801847/102719518-e9608a80-42ee-11eb-8f94-641e3e00b217.png):

Yes, I removed the comma and solved it ... any other way by upgrading to any specific build

**Comment by amanganiello90** [comment]
> 
> 
> Hi @JavierFuentes,
> thanks for the issue!
> So I have tried to replicated it.
> 
> I first generated the application according your yo-rc.json, and after run import-jdl with your model (always with --skipInstall).
> Finally my app.module is:
> 
> ```
> @Module({
>   imports: [
>     TypeOrmModule.forRoot(ormconfig),
>     ServeStaticModule.forRoot({
>       rootPath: config.getClientPath()
>     }),
>     AuthModule,
>     RegionModule,
>     CountryModule,
>     LocationModule,
>     DepartmentModule,
>     TaskModule,
>     EmployeeModule,
>     JobModule,
>     JobHistoryModule
>     // jhipster-needle-add-entity-module-to-main - JHipster will add entity modules here, do not remove
>   ],
>   controllers: [
>     // jhipster-needle-add-controller-module-to-main - JHipster will add controller modules here, do not remove
>   ],
>   providers: [
>     // jhipster-needle-add-service-module-to-main - JHipster will add service modules here, do not remove
>   ]
> })
> export class AppModule {}
> ```
> 
> I don't see the issue...
> 
> Beside there is an integration test that covers your scenario: https://github.com/jhipster/generator-jhipster-nodejs/runs/1548930380

Hi @ifelse-codes, I don't know how you have this issue, because the previous steps (also performed in a github action pipeline) do not present that.
