### ISSUE TITLE
Share model Interfaces between client and server to ensure consistency

### ISSUE THREAD

**Issue by JavierFuentes** [jhipster/generator-jhipster-nodejs#200]
**Is your feature request related to a problem? Please describe.**
I wonder if it would be possible that in nHipster projects the Interfaces of the models could be defined following the DRY principle and in such a way that they can be applied to both the Client and Server Classes to guarantee at all times the coherence between both layers of the application.

**Describe the solution you'd like**
Share model Interfaces definition between client and server layers.

**Comment by amanganiello90** [comment]
Ho @JavierFuentes, as I said on the #199, the client and the server sides are indipendent from each other, for the simple reason that the client is inherited by jhipster main generator, while the backend is generated by NHipster.

**Comment by amanganiello90** [comment]
If there are other questions, I consider close this ticket. However, feel you free to comment or open other issues. You are welcome!
