### ISSUE TITLE
TypeORM future?

### ISSUE THREAD

**Issue by capioc** [jhipster/generator-jhipster-nodejs#212]
Considering the state of TypeORM project, the development of which is almost dead, what is its future regarding nHipster?

Is it still considered stable and production ready?

Thank you

**Comment by amanganiello90** [comment]
Hi @capioc,
Thanks for the interest!
TypeORM is a framework to support ORM for database in NHipster, but it is not the entire app.
NHipster is based on [NestJS](https://nestjs.com/), and for the database now typeorm support all db types without any problems (https://github.com/typeorm/typeorm/blob/master/docs/entities.md#entities).

So it is not a problem that typeORM is already dead. Besides we are now development the new nhipster 2.0.0 with vuejs and improvements #211

**Comment by capioc** [comment]
Hi @amanganiello90 , thanks for the prompt reply!

I know that NHipster is so much more than TypeORM, but it's such a crucial part of its architecture. I am not implying that NHipster is going to die.

I was just beginning a new project and after using JHipster at work I really wanted to give NHipster a try. However, I saw that TypeORM having so many open issues and a discussion that its maintenance is not sustainable and consistent. And a lot of people don't feel confident to use it for new projects.

That's why I wanted to hear your opinion on that and if there are thoughts to integrate a different ORM solution in the future.

**Comment by amanganiello90** [comment]
At this moment the typeORM usage in NHipster covers all the features (sql, relationship and mongodb). So for now there aren't problems in NHipster for its. Maybe in future if it is necessart, we could be evaluate another solution, but now I don't know.

**Comment by capioc** [comment]
Alright thank you very much!

I will start my project with NHipster and I will report back if any issue arise

**Comment by amanganiello90** [comment]
For nodejs there are these other following ORM project used in nodejs development:
- sequelize
- bookshelf
- waterline
- objection

Nothing have the db support as TypeORM (it supports al lot of database with robust relationship mapping).

If you could suggest any other solutions, it will be great.
Thanks.

**Comment by amanganiello90** [comment]
I hope that my explanation is been clear. So I consider this question/issue resolved.
