### ISSUE TITLE
Nhipster 2.0.0-beta.1 release

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#218]
This is a placeholder ticket to remember the first 2.0.0-beta.1 NHipster release.

Could someone (@jdubois, @pascalgrimaud or @deepu105) create e new example repo named **jhipster-sample-app-nodejs-vuejs** in way that I can push the new app? Thanks

**Comment by deepu105** [comment]
done

**Comment by amanganiello90** [comment]
Thanks.
- Released: https://www.npmjs.com/package/generator-jhipster-nodejs/v/2.0.0-beta.1
- Added new vuejs app: https://github.com/jhipster/jhipster-sample-app-nodejs-vuejs/tree/v2.0.0-beta.1
- Updated: https://github.com/jhipster/jhipster-sample-app-nodejs/tree/v2.0.0-beta.1
- Updated: https://github.com/jhipster/jhipster-sample-app-nodejs-oauth2/tree/v2.0.0-beta.1
