### ISSUE TITLE
Question: Input actions synchronize between 2 different browser windows for client app, when run npm start and start:app scripts

### ISSUE THREAD

**Issue by pwujek** [jhipster/generator-jhipster-nodejs#223]
## Overview of the issue
This is a very weird issue, I would be surprised if you have encountered this. Originally I thought this was caused by some Linux Gtk library issue, but now we know that it occurs in Windows as well. 

If I have my app open in > 1 browser windows inputs can synchronize between the windows, even if some are Firefox and others are Chrome. They can be any mixture of Chrome and Firefox, all Chrome, all Firefox, some Chrome and some Firefox.

The same issue has been encountered in Ubuntu 20.10 and Windows 10, as long as all the browsers/windows are running on the same desktop.

The synchronization only happens if the same app is running on all.

* scrollable divs scroll in any non-focused window in sync with the browser that has focus whether using the mouse scroll wheel or dragging the scroll bar.
* input values typed into input fields are mirrored in the same input fields in any non-focused window
* dropdown lists open and are selected in sync
* sometimes input into only 1 of the windows causes the synchronization, other times input into any of the windows is sync'd by the other windows.

## Motivation for or Use Case
I would like to prevent this from happening in the production environment.

## Reproduce the error (dev mode)
1. npm run start:app
2. npm run start
3. Open the app in > 1 browser window
4. scroll the app window in 1 window, and type into different input fields while observing the other windows

## JHipster Version(s)
6.8.0
Environment: React, SQL

## O/S versions
* Windows 10
* Ubuntu 20.10

## Browser versions (Ubuntu)
* FireFox - 88.0 (64-bit)
* Chrome - 91.0.4472.27 (Official Build) beta (64-bit)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by amanganiello90** [comment]
Hi @pwujek, thanks for the issue.
However, your issue it's very strange, and I don't believe that it is related to the application. Maybe it's a browser issue

**Comment by amanganiello90** [comment]
However, please use the latest 2.0.0-beta.1 nhipster version, and read carefully the development section: https://github.com/jhipster/jhipster-sample-app-nodejs/blob/main/README.md#development

It is explained in the statement **Run the following commands in two separate terminals to create a blissful development experience where your browser auto-refreshes**

**Comment by pwujek** [comment]
Thank you for your help.

The suggested changes did not stop the synchronization, but in this test the input fields and dropdown were not sync'd.

https://user-images.githubusercontent.com/1900015/117449811-65f6ad00-af0e-11eb-96cd-2ad1805c146f.mp4
