### ISSUE TITLE
Entity name duplicated into app.module.ts imports with additional comma every time entity updated

### ISSUE THREAD

**Issue by TRIGGEREDcoder** [jhipster/generator-jhipster-nodejs#224]
**Describe the bug**
Entity name duplicated into app.module.ts imports every time entity updated, the name can appear several times.

**To Reproduce**
nHipster entity myEntity -> regenerate
look at server/src/app.module.ts

**Expected behavior**
Existing entity names should not be duplicated in import.

**Screenshots**
![image](https://user-images.githubusercontent.com/43340158/117607515-c3426680-b179-11eb-90f5-f9928664b811.png)

**Desktop:**

OS: Windows 10 Pro
nHipster 6.10.3

**NHipster configuration**

nhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! No custom sharedOptions found within blueprint: generator-jhipster-nodejs at C:/Users/dsamarli/Desktop/NodeHipsterII/node_modules/generator-jhipster-nodejs
INFO! No custom commands found within blueprint: generator-jhipster-nodejs at C:/Users/dsamarli/Desktop/NodeHipsterII/node_modules/generator-jhipster-nodejs
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
nodeapplication@0.0.1-SNAPSHOT C:\Users\dsamarli\Desktop\NodeHipsterII
+-- generator-jhipster@7.0.0
`-- generator-jhipster-nodejs@2.0.0-beta.1
  `-- generator-jhipster@7.0.0  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0-beta.1"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0-beta.1"
      }
    ],
    "applicationType": "monolith",
    "baseName": "Nodeapplication",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1620306709800,
    "serverPort": "8081",
    "packageName": "com.jhipster.node",
    "databaseType": "sql",
    "devDatabaseType": "sqlite",
    "prodDatabaseType": "mysql",
    "authenticationType": "jwt",
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/jhipster/node",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "serviceDiscoveryType": false,
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "al"],
    "cacheProvider": "ehcache",
    "buildTool": "maven",
    "enableHibernateCache": true,
    "reactive": false,
    "lastLiquibaseTimestamp": 1620370911000,
    "entities": ["Owner", "Car", "Bike", "Author", "Book", "Employee"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Owner {
  ownerName String
}
entity Car {
  carName String
  carOwnerName String
}
entity Bike {
  bikeName String
}
entity Author {
  authorName String
}
entity Book {
  bookName String
}
entity Employee {
  employeeName String
  empAddress String
}
relationship OneToOne {
  Author{book(bookName)} to Book
}
relationship OneToMany {
  Owner{bookowner} to Book{ownerbook(ownerName)}
}
relationship ManyToOne {
  Car{owner(ownerName)} to Owner
  Bike{owner(ownerName)} to Owner
}

service Owner, Bike with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

git version 2.25.0.windows.1

node: v12.18.4

npm: 6.14.8

**.yo-rc.json**
{
  "generator-jhipster": {
    "blueprints": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0-beta.1"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0-beta.1"
      }
    ],
    "applicationType": "monolith",
    "baseName": "Nodeapplication",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1620306709800,
    "serverPort": "8081",
    "packageName": "com.jhipster.node",
    "databaseType": "sql",
    "devDatabaseType": "sqlite",
    "prodDatabaseType": "mysql",
    "authenticationType": "jwt",
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/jhipster/node",
    "jwtSecretKey": "YWFjMjdiMmU4NjI3MGRjYmI4M2Y2Y2U0NjAyYzU3NTM4NDMzNTg4NzUyZjUwMTExYTk1N2I4NjQ3MWQ1M2FhODkzYjgwYmM2MDc4Y2I4OWRkYjU0MjkzMDQ0MzU0MGI3ZjQwYmM3ZDE4OWZjNWJlMmZiOTU1ZTFjMGUyOWFlODk=",
    "serviceDiscoveryType": false,
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "al"],
    "cacheProvider": "ehcache",
    "buildTool": "maven",
    "enableHibernateCache": true,
    "reactive": false,
    "lastLiquibaseTimestamp": 1620370911000,
    "entities": ["Owner", "Car", "Bike", "Author", "Book", "Employee"]
  }
}

**Comment by amanganiello90** [comment]
duplicated of #219. Use the main branch code or wait for the next release. Thanks

**Comment by TRIGGEREDcoder** [comment]
Yes, this issue has been raised previously as well and it was closed. So I raised it again as the same issue I was facing even after beta version installation for nhipster. Will wait for the next release.

Thanks.
