### ISSUE TITLE
Not able to create entity with one-to-many relationship if the other entity is not present

### ISSUE THREAD

**Issue by TRIGGEREDcoder** [jhipster/generator-jhipster-nodejs#225]
**Describe the bug**
When trying to create a new entity with one-to-many relationship with an entity which is yet to be created, it gives the error _ERROR! Error looking for otherEntity otherEntityName_

**To Reproduce**
nHipster entity myEntity 
when prompted below questions,
? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? Address
? What is the name of the relationship? address
? What is the type of the relationship? one-to-many
? What is the name of this relationship in the other entity? employer

**Expected behavior**
It should let us create the entity with the entity field and relationship details even if the other entity is not present yet as the same is allowed in **jhipster entity entityName**
https://www.jhipster.tech/managing-relationships/ 

**Screenshots**
![image](https://user-images.githubusercontent.com/43340158/117608831-790eb480-b17c-11eb-83e4-5e2f854e1d49.png)

**Desktop (please complete the following information):**
OS: Windows 10 Pro
nHipster 6.10.3

**NHipster configuration**

nhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! No custom sharedOptions found within blueprint: generator-jhipster-nodejs at C:/Users/dsamarli/Desktop/NodeHipsterII/node_modules/generator-jhipster-nodejs
INFO! No custom commands found within blueprint: generator-jhipster-nodejs at C:/Users/dsamarli/Desktop/NodeHipsterII/node_modules/generator-jhipster-nodejs
Welcome to the JHipster Information Sub-Generator

JHipster Version(s)
nodeapplication@0.0.1-SNAPSHOT C:\Users\dsamarli\Desktop\NodeHipsterII
+-- generator-jhipster@7.0.0
`-- generator-jhipster-nodejs@2.0.0-beta.1
  `-- generator-jhipster@7.0.0  deduped

JHipster configuration, a .yo-rc.json file generated in the root folder
.yo-rc.json file
JDL for the Entity configuration(s) entityName.json files generated in the .jhipster directory
JDL entity definitions
Environment and Tools
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

git version 2.25.0.windows.1

node: v12.18.4

npm: 6.14.8

.yo-rc.json
{
"generator-jhipster": {
"blueprints": [
{
"name": "generator-jhipster-nodejs",
"version": "2.0.0-beta.1"
}
],
"otherModules": [
{
"name": "generator-jhipster-nodejs",
"version": "2.0.0-beta.1"
}
],
"applicationType": "monolith",
"baseName": "Nodeapplication",
"jhipsterVersion": "7.0.0",
"skipClient": false,
"skipServer": false,
"skipUserManagement": false,
"skipCheckLengthOfIdentifier": false,
"skipFakeData": false,
"jhiPrefix": "jhi",
"entitySuffix": "",
"dtoSuffix": "DTO",
"testFrameworks": [],
"pages": [],
"creationTimestamp": 1620306709800,
"serverPort": "8081",
"packageName": "com.jhipster.node",
"databaseType": "sql",
"devDatabaseType": "sqlite",
"prodDatabaseType": "mysql",
"authenticationType": "jwt",
"clientFramework": "angularX",
"withAdminUi": true,
"clientTheme": "none",
"enableTranslation": true,
"nativeLanguage": "en",
"packageFolder": "com/jhipster/node",
"jwtSecretKey": "YWFjMjdiMmU4NjI3MGRjYmI4M2Y2Y2U0NjAyYzU3NTM4NDMzNTg4NzUyZjUwMTExYTk1N2I4NjQ3MWQ1M2FhODkzYjgwYmM2MDc4Y2I4OWRkYjU0MjkzMDQ0MzU0MGI3ZjQwYmM3ZDE4OWZjNWJlMmZiOTU1ZTFjMGUyOWFlODk=",
"serviceDiscoveryType": false,
"websocket": false,
"searchEngine": false,
"messageBroker": false,
"clientPackageManager": "npm",
"clientThemeVariant": "",
"languages": ["en", "al"],
"cacheProvider": "ehcache",
"buildTool": "maven",
"enableHibernateCache": true,
"reactive": false,
"lastLiquibaseTimestamp": 1620370911000,
"entities": ["Owner", "Car", "Bike", "Author", "Book", "Employee"]
}
}

**Comment by amanganiello90** [comment]
Thanks for the issue. I will investigate on it.
