### ISSUE TITLE
Remove in query user api the unencrypted password exposed

### ISSUE THREAD

**Issue by glutengo** [jhipster/generator-jhipster-nodejs#232]
**Describe the bug**
At numerous places in the application, the value of the password property of the user entity are delivered in plain text. This affects (incomplete):
- GET /api/admin/users
- GET /api/account

The password should not be readable to anyone, not even the admin. The password should be at least encrypted, but it would be better if it was not included in the serialized user object at all. 

**To Reproduce**

1. Generate a new app via nhipster
2. Select the default option for every question
3. Login as admin
4. Go to User Management
5. Open Dev Tools Check the returned data for the listed endpoints

**Expected behavior**
The password is not part of the serialized user object.

**Screenshots**
![Screenshot 2021-05-31 at 10 58 56](https://user-images.githubusercontent.com/14246032/120168499-3716e280-c1ff-11eb-9a71-702b875f4741.png)

**Desktop (please complete the following information):**

-   OS: iOS 11.3
-   NHipster Version 2.0.0-beta.1

**NHipster configuration**

**Additional context**
I discovered the problem while working on #214

**Comment by glutengo** [comment]
I would suggest preventing this by not reading the password from the database as suggested here: https://stackoverflow.com/a/62957519/2202290

However I also noticed that the password is encrypted (rather than hashed). This is not considered best practise because the administrators / developers / ... could steal the password of the users by decrypting the password. Background Information: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#background

**Comment by amanganiello90** [comment]
Hi @glutengo, thanks for the suggestion!.
So, the encryption field is performed automatically by TypeOrm. According to you, maybe we could delete password in the object returned in the controller GET apis.

**Comment by glutengo** [comment]
I think it would be good to split it into two issues:
The first (this one) handles what is returned by the API. If we do not read the password from the database at all, it will never be included in any response of the controllers. My PR handles this.

The second issue would be about password encryption / hashing. As stated above, I think it would be better if the password was hashed so that there is no way to decrypt the password.

**Comment by amanganiello90** [comment]
Ok, it's ok the first PR, you can open a new issue for the second point.

**Comment by gmarziou** [comment]
Maybe you should consider following some practices from JHipster java:

* process to report and address security issues: https://www.jhipster.tech/2019/09/13/jhipster-release-6.3.0.html#jhipster-release-v630
* carefully select algorithm. For instance, in the past JHipster was using [https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/.html](Spring StandardPasswordEncoder) that uses SHA-256 hashing with 1024 iterations which is no longer considered secure. Now it uses [BCryptPasswordEncoder](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoder.html)

**Comment by glutengo** [comment]
@gmarziou I agree, the [bcrypt library](https://www.npmjs.com/package/bcrypt is the standard for storing passwords in Node.js web apps too. I have created issue #234 for that.
