### ISSUE TITLE
No conection with okta

### ISSUE THREAD

**Issue by alexander090496** [jhipster/generator-jhipster-nodejs#249]
Hello, I have an application generated with Jhipster (web) with a user Auth "Okta".  From my Jhipster application it directs well to my Okta authenticator, it performs the login normally but when I return to my Jhipster application it does not register the user in my database of my web application and throws the following error:
![okta](https://user-images.githubusercontent.com/30643372/131135127-185eb505-f363-4472-be3f-22c3808267c5.PNG)

**Comment by amanganiello90** [comment]
I close this issue because it is related to JHipster project (not NHipster). Thanks
