### ISSUE TITLE
FIX: node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by enixlabs** [jhipster/generator-jhipster-nodejs#253]
**Is your feature request related to a problem? Please describe.**

```code
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! bcrypt@5.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bcrypt@5.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-09T10_22_52_173Z-debug.log
WARNING! Install of server dependencies failed!
To install your server dependencies manually, run: cd server && npm install
```
**Describe the solution you'd like**

Yarn to be used instead of NPM to install dependencies, as the issue is with NPM causing the problem. I have tested this across multiple systems, WSL2, Docker, Barebones and VM and all have had the same issues with installing "Bcrypt" using NPM (Even as a standalone). We've also found that NPM is skipping the installation of packages as well.

**Describe alternatives you've considered**

"Node-GYP" appears to be a massive industry problem right now and no real clear solution and only suggestive fixes that are not always fixing the issue, as it then arrives again from an update and whilst using NPM. We've found that Yarn is the only solution to get around issues like this. We have issues with other NPM packages as well, as an example Husky won't install.

**Additional context**

**Comment by amanganiello90** [comment]
Hi @enixlabs , thanks for the issue! 
Maybe you have to check your nodejs/npm version, because in the github actions we haven't troubles with npm.

**Comment by enixlabs** [comment]
> Hi @enixlabs , thanks for the issue!
> Maybe you have to check your nodejs/npm version, because in the github actions we haven't troubles with npm.

```code
Yarn to be used instead of NPM to install dependencies, as the issue is with NPM causing the problem. I have tested this across multiple systems, WSL2, Docker, Barebones and VM and all have had the same issues with installing "Bcrypt" using NPM (Even as a standalone). We've also found that NPM is skipping the installation of packages as well.
```
^ - As per the above, just because something works for you, it isn't working for everyone and issues with "Node-GYP" have been around now for about 5 years and no fix for the various issues it raises, which include installing of packages. 

I've spent the last month researching the issues that everyone is having with "Node-GYP" and I've found the fix is "Yarn" and I've also found, that there are a lot of mitigating reasons to why NPM isn't working properly for some and it can also be intermittent on when and how it happens. **It's a common issue**

**Comment by amanganiello90** [comment]
Thanks for the reply, but I am not understanding the issue. On the github actions we use npm and not yarn  with no problems.  Besides we don't install any additional tools on these pipelines. You have to check your nodejs version, see the pipelines:https://github.com/jhipster/generator-jhipster-nodejs/runs/3526968041

If you suggest to remove bcrypt, for now it's not possibile because it is necessary crypting passwords on db. 

Thanks

**Comment by enixlabs** [comment]
All issues are fixed - fixed by modifying user permissions on both server and local machine.
