### ISSUE TITLE
How get current logged user

### ISSUE THREAD

**Issue by Diandson** [jhipster/generator-jhipster-nodejs#256]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amanganiello90** [comment]
Hi, thanks for the issue!! If you want the current logged user, you have to call the get account api :https://github.com/jhipster/generator-jhipster-nodejs/blob/69cd3b9282a3951636b4ba603f0da992c0dd7f0c/generators/server/templates/server/src/web/rest/account.controller.ts.ejs#L59

**Comment by Diandson** [comment]
I see that! 
But 
Don't vexe. I need to get it from the back-end .
The controller @request param to provide.
if there I stuck in.

**Comment by Diandson** [comment]
excuse me i just understand what that mean.

I fix it. Thanks you too much
