### ISSUE TITLE
Running jhipster-generator-nodejs via Docker give error

### ISSUE THREAD

**Issue by threedliteguy** [jhipster/generator-jhipster-nodejs#258]
Running jhipster-generator-nodejs using the Docker instructions in the readme.md returns an error.
Dependency resolution for nest fails and there is a lint error that prevents it from completing.  However some files are generated.
I am using MacOS and Docker Desktop.  I did notice it appears to be still using node 12, would 16 work better?

**Comment by mserravalle92** [comment]
i'm having some problem with the docker, npm install fails when tried install bcrypt.
<img width="1029" alt="Captura de Pantalla 2023-01-30 a la(s) 14 14 57" src="https://user-images.githubusercontent.com/12702310/215547133-b13a4f91-893d-4dba-b665-6822f8d53cf6.png">
