### ISSUE TITLE
Add information on jhipster official page about the development of this blueprint

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#27]
Hi @deepu105,
We are quite near to release the first version of this blueprint. Could you add a section in the [offical blueprint jhipster page](https://www.jhipster.tech/modules/official-blueprints/) ?
There would be good in order to give attention and pleasure to the all development community. Thanks a lot in advance.

**Comment by amanganiello90** [comment]
For this, I have created the [PR](https://github.com/jhipster/jhipster.github.io/pull/775) to update the official site. Could you merge that?

**Comment by deepu105** [comment]
Done merged. Thanks

Thanks & Regards,
Deepu

**Comment by amanganiello90** [comment]
Thanks a lot!
