### ISSUE TITLE
Update to latest node (lts) and package versions.

### ISSUE THREAD

**Issue by pahlers** [jhipster/generator-jhipster-nodejs#278]
**Is your feature request related to a problem? Please describe.**

It would be good to update **nodejs** and the **packages** to the **latest version**.
Current `npm audit` shows **31 vulnerabilities** (12 moderate, 13 high, 6 critical). That's a bad sign.

**Describe the solution you'd like**
Update nodejs to **v16** (and support v18) and update all packages to the latest version.

I started with it and replaced a lot of `require` with `import` (eazy). But now I'm stuck because I don't understand the inner working of the application. It can't load `cli/commands`, because there isn't one in the project. But how does that work in the current version ???.

**Describe alternatives you've considered**
Sorry to say, but remove the support of nodejs from jHipster. This isn't safe.

**Comment by pahlers** [comment]
Forgot to say. Excellent project and code. :+1:

**Comment by amanganiello90** [comment]
Hi @pahlers, thanks for the interest.
However, I don't understand your issue.
A command line file is added in **cli folder**, and a PR to upgrade blueprint is in review (https://github.com/jhipster/generator-jhipster-nodejs/pull/274)

But, there are some error to resolve on github actions, so the upgrade is not so mandatory for now.

**Comment by pahlers** [comment]
I'm confused too. I don't see any commands.js in de cli folder. See the screenshot. Am I linking the **generator-jhipster** project incorrect?

![image](https://user-images.githubusercontent.com/432408/191101934-05c8b8cc-b156-49dd-a6c5-576c80a9aff4.png)

Nice to see there is already a update. Is there a way I can help?

**Comment by pahlers** [comment]
I will give it a go. I have no experience with Github. More with Jenkins and Gitlab. But how hard can it be! (Famous last words)
