### ISSUE TITLE
takes too much time to run the code after any change

### ISSUE THREAD

**Issue by Othman2001** [jhipster/generator-jhipster-nodejs#292]
**Describe the bug**
we are using this generator to generate endpoints code with nest  however our project is pretty large and sometimes we need to customize the end points, and when adding any change to the code in the endpoints it takes up to 15 min to re start the nodemon so i don't know where is the problem  but i think that it re compiles the all modules again.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [windows]
-   Browser [e.g. chrome, safari]

**NHipster configuration**

**Comment by amanganiello90** [comment]
Thanks for the interest.
I think that is an issue related to nestjs version and your large project. So it is not a bug of generator.

**Comment by mahdikeshavarz903** [comment]
> **Describe the bug** we are using this generator to generate endpoints code with nest however our project is pretty large and sometimes we need to customize the end points, and when adding any change to the code in the endpoints it takes up to 15 min to re start the nodemon so i don't know where is the problem but i think that it re compiles the all modules again.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [windows]
> * Browser [e.g. chrome, safari]
> 
> **NHipster configuration**

You can use TS_NODE_TRANSPILE_ONLY=true to solve the problem

**Comment by ayoubaayoub** [comment]
just  run npm run start:dev instead of npm run start.
