### ISSUE TITLE
This needs support for macOS Ventura

### ISSUE THREAD

**Issue by davidauza-engineer** [jhipster/generator-jhipster-nodejs#295]
**Describe the bug**
This application has a [dependency](https://github.com/jhipster/generator-jhipster-nodejs/blob/6ac167584ac4c7a73e13abb72d95cd9d0bba6830/package-lock.json#L5182-L5186) on [macos-release](https://github.com/sindresorhus/macos-release/blob/main/index.js).

The `package-lock.json` file shows it relies on version `2.5.0`. That version doesn't include the map for macOS Ventura. We need to updated it to use `3.1.0`.

As a workaround,  to make it work, I had to manually add the line below in my local install:

https://github.com/sindresorhus/macos-release/blob/74d928f6cc6b8b0d302d6900ad395fc51c04bf39/index.js#L4

**To Reproduce**
After installing all the requirements, run `nhipster` on a mac with macOS Ventura.

**Expected behavior**
The command should run with no issues.

**Desktop (please complete the following information):**

-   OS: macOS Ventura 13.2

**Additional context**
This should be as easy as updating the dependency on `macos-release` to `3.1.0` but frankly I'm not quite sure on the best way to do it.

@amanganiello90

**Comment by amanganiello90** [comment]
Hi @davidauza-engineer , `macos-release` is a transitive dependencies of `insight` used by the base `generator-jhipster`,
So I can't updata that without updating jhipster

**Comment by mraible** [comment]
This will be fixed in the next release.
