### ISSUE TITLE
Where to find contribution roadmap?

### ISSUE THREAD

**Issue by hadirsa** [jhipster/generator-jhipster-nodejs#3]
To help in development, could you please share road map link?
@amanganiello90

**Comment by amanganiello90** [comment]
Yes, now I provide a roadmap file on the master branch in order to develop the generator features

**Comment by amanganiello90** [comment]
@hadirsa, you can find the [ROADMAP](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/ROADMAP.md).
Please start to contribute to the **feature one**. Thanks

**Comment by hadirsa** [comment]
That sounds great. To start, I think this  ROADMAP is enough. I'll do my best. @amanganiello90
