### ISSUE TITLE
A way to provide schema migration in dev startup

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#30]
A way to include mongodb in prod with db migration schema

**Comment by amanganiello90** [comment]
Remember that, according the answer, it will be a prod db connection with sqlite (or mongodb)..

``
const defaultOptions = {
  type: 'postgres',
  port: 5432,
  username: 'user',
  password: 'password',
  database: 'db',
  synchronize: true,
};

@Module({
  imports: [
    TypeOrmModule.forRoot({
      ...defaultOptions,
      host: 'photo_db_host',
      entities: [Photo],
    })
``
So, according the environment (dev or prod), the connection must be changed. Please attention that in dev mode there is always the sqlite db.

**Comment by amanganiello90** [comment]
The issue is not more an optional, because we have to provide a migration with typeORM for scripts in dev mode running for sqlite

**Comment by amanganiello90** [comment]
Consider [feature/migration-db](https://github.com/jhipster/generator-jhipster-nodejs/tree/feature/migration-db) and this **src/ormconfig.ts**:

```
import { ConnectionOptions } from 'typeorm'; const config: ConnectionOptions = {  type: 'postgres',  host: process.env.POSTGRES_HOST,  port: Number(process.env.POSTGRES_PORT),  username: process.env.POSTGRES_USER,  password: process.env.POSTGRES_PASSWORD,  database: process.env.POSTGRES_DB,  entities: [    __dirname + '/../**/*.entity{.ts,.js}',  ],  cli: {    migrationsDir: 'src/migrations',  }}; export = config;
```

**Comment by deepu105** [comment]
I wouldn't want to have another question for this. Can we do it with flag
or vis JDL?

Thanks & Regards,
Deepu

**Comment by amanganiello90** [comment]
Hi @deepu105,
now for this blueprint, in the server generator there are only two questions: _serverPort_ and _mongoProdDatabase_ . The other prompts questions for the server generation are been delated, because in this blueprint they haven't sense to be due to their java spring meaning. So if you answer to yes for the *mongoProdDatabase* there will generated the config for this, otherwise the sqlite is the default. So be careful that there aren't other database questions.

**Comment by deepu105** [comment]
Ok in that case I

Thanks & Regards,
Deepu
