### ISSUE TITLE
Migrate to JHipster v8

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#300]
**Overview of the feature request**
According https://github.com/jhipster/generator-jhipster/issues/23449 JHipster v8 is getting close, we should migrate and make sure everything is working correctly.

Major tasks:
- [ ] convert blueprint to v8 according the jhipster v8 prompt
- [ ]  Check, test and fix entity jdl generation
- [ ]  Check, test and fix angular client generation
- [ ]  Check, test and fix react client generation
- [ ]  Check, test and fix vue client generation
- [ ]  Check, test and fix ci-cd generation
- [ ]  Check all test integrations and fix github actions

**Related issues or PR**
- [x]  Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
Is something missing for a new release?

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/180755

**Comment by DanielFran** [comment]
@mshima approved

**Comment by mshima** [comment]
Thanks
