### ISSUE TITLE
Update NestJS packages.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-nodejs#349]
NestJS package are outdated and peerDependencies should be honored.

An initial PR is https://github.com/jhipster/generator-jhipster-nodejs/pull/329.
Seems NestJS 8 had some behavior changes and migration needs more work.

**Comment by mshima** [comment]
I haven’t managed to make the db changelogs to apply.
Anyone feel free to take from where I’ve stopped.

**Comment by crossz** [comment]
time to go for Nest.js v10.

**Comment by mshima** [comment]
@DanielFran bug bounty claimed https://opencollective.com/generator-jhipster/expenses/228476
