### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by subbu519** [jhipster/generator-jhipster-nodejs#48]
**Describe the bug**
Already run the command "npm install -g generator-jhipster-nodejs" but got error when run "jhipster --blueprint nodejs"

      throw er; // Unhandled 'error' event
      ^

Error: The ←[33mgenerator-jhipster-nodejs←[39m blueprint provided is not installed. Please install it using command ←[33mnpm i -g generator-jhipster-nodejs←[39m.
    at Environment.error

**Comment by amanganiello90** [comment]
Hi, 
thanks for the feedback!
Probably you don't have correctly installed the generator, and then you have to retry.
Please check these questions:
1.  What version of node are you using? Execute ```node -v```... the version recommended is above 8.10.x
2. Check if the generator is installed, executing ```npm list -g generator-jhipster-nodejs```, it will display:
> C:\Users\xxxxxxx\AppData\Roaming\npm
└── generator-jhipster-nodejs@1.0.0-alpha.2
If is not installed:
> C:\Users\xxxxxxx\AppData\Roaming\npm
└──(empty)

3. So, retry with ```npm i -g generator-jhipster-nodejs```, if all it's ok you will see:

![immagine](https://user-images.githubusercontent.com/20536757/65308692-e5ddd100-db8a-11e9-8826-dfb21ad457b1.png)

**Comment by subbu519** [comment]
Ok, But got same Issue
![Screenshot (61)](https://user-images.githubusercontent.com/32788300/65314236-8cd66300-dbb3-11e9-8e2c-2bbfd9f0ed3c.png)

**Comment by amanganiello90** [comment]
You can switch a older version of nodejs (8.10.x)? I see that you use the 10.x.
On windows you can use [nvm](https://github.com/coreybutler/nvm-windows) to use various node.js version. After reinstall the generator.

**Comment by subbu519** [comment]
Still it's not working
![Screenshot (64)](https://user-images.githubusercontent.com/32788300/65320545-b9907780-dbbf-11e9-8150-06a48224243c.png)

**Comment by amanganiello90** [comment]
Hi @subbu519 ,
the command without blueprint nodejs option is only ```jhipster```.

**Comment by subbu519** [comment]
when  I am using "jhipster" command it generates Java Project

**Comment by amanganiello90** [comment]
> 
> 
> when I am using "jhipster" command it generates Java Project

Yes, there was a test to understand if jhipster standard cli is installed correctly.

**Comment by subbu519** [comment]
> Hi @subbu519 ,
> the command without blueprint nodejs option is only `jhipster`.
> 
> After try also the development commands from [CONTRIBUTING GUIDE](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/CONTRIBUTING.md)

It s done when I am following this one

**Comment by subbu519** [comment]
thankyou @amanganiello90

**Comment by amanganiello90** [comment]
But It's strange that the install from the npm registry not recognise that generator in the running phase. I have tested the installation in different machines, maybe you have not installed globally yeoman or some jhipster dependency packages. Thank you.

**Comment by venkataramkishore** [comment]
Hi I have followed the same steps as suggested above conversation still i have the same issue:
The following are the versions in picture

![image](https://user-images.githubusercontent.com/14111132/65449966-c203df00-de59-11e9-82b0-468ca58c9bc4.png)

**Comment by amanganiello90** [comment]
Hi @venkataramkishore,
In your screen there aren't any errors. It works, there is the first question on the application type.

**Comment by venkataramkishore** [comment]
I am trying to start Nodejs blueprint not Java, so according to your documentation i am expecting NHIPSTER not JHIPSTER? 
Please suggest if otherwise.

**Comment by amanganiello90** [comment]
> I am trying to start Nodejs blueprint not Java, so according to your documentation i am expecting NHIPSTER not JHIPSTER?
> Please suggest if otherwise.

After you have answered the application type and the app name, it will display NHipster logo and the related questions. If you read your prompt, there is the **INFO: options: blueprint: nodejs**. So jhipster has found nodejs blueprint. It works.

**Comment by venkataramkishore** [comment]
Hi @amanganiello90 , Yes indeed it worked !! 
Command also suggest using **blueprints** not _blueprint_
Should these details be updated in your documentation?
The following image is the output of command flow:
 
![image](https://user-images.githubusercontent.com/14111132/65489909-c536b380-dec9-11e9-8f29-9a9ee5a1c541.png)

**Comment by amanganiello90** [comment]
Hi @venkataramkishore,
Yes, I will update after changing with the new version of the jhipster cli. Thanks
