### ISSUE TITLE
how do i connect sql database ?

### ISSUE THREAD

**Issue by ameinabdi** [jhipster/generator-jhipster-nodejs#50]
How can read about sql db connection? 

when i select mysql database i got this error to start project

![Screenshot 2019-09-20 at 2 33 36 PM](https://user-images.githubusercontent.com/31644919/65324042-b099a900-dbb3-11e9-87e3-392b649e6244.png)

**Comment by amanganiello90** [comment]
Hi @ameinabdi,
there is the [orm.config.ts](https://github.com/jhipster/jhipster-sample-app-nodejs/blob/v1.0.0-alpha.2/server/src/orm.config.ts) where is stored db information. For dev it will be always sqlite created on app startup.

**Comment by ameinabdi** [comment]
i have added my info about database in that file but i still it doesn't work so did you test sql before now ?

**Comment by amanganiello90** [comment]
What db have you ever choosen in the related question?

**Comment by ameinabdi** [comment]
mysql

**Comment by amanganiello90** [comment]
What command are you using to startup application? Write in order the commands.

**Comment by ameinabdi** [comment]
jhipster --blueprint nodejs

**Comment by amanganiello90** [comment]
That command is for generation.. I said about startup.. however for mysql prod db, the connection created is:
```
ormconfig = {
        name: 'default',
        type: 'mysql',
       url: 'mysql://localhost:27017/<your-app-name>,
        synchronize: true,
        logging: false,
        entities: [__dirname + '/domain/*.entity{.ts,.js}'],
    };
```

Change url with your mysql instance.

**Comment by ameinabdi** [comment]
i run this command inside the server folder 
npm start

**Comment by amanganiello90** [comment]
> 
> 
> i run this command inside the server folder
> npm start

Ok, so you are using sqlite dev db, not mysql

**Comment by ameinabdi** [comment]
but i don't need to use sqlite. i need to use mysql database

**Comment by amanganiello90** [comment]
Then, replace in the if of Prod section [the mysql source configuration](https://github.com/jhipster/generator-jhipster-nodejs/issues/50#issuecomment-533518916) and run:

``` set NODE_ENV=prod&&npm start ```

**Comment by ameinabdi** [comment]
okey thanks a lot mr @amanganiello90
