### ISSUE TITLE
Support okta oauth2 security feature

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#52]
As @mraible asked me, we would provide support to choose instead of simple jwt authentication, the oauth2 protocol in the related question. Passport can already allow this configuration with the correct strategy class. Please refer to [oauth2 server](https://github.com/jersonsw/oauth2-server) or [nestJS oauth2 app](https://github.com/bojidaryovchev/nest-angular)

**Comment by amanganiello90** [comment]
I have tested and developed it, for the next days I will add new templates.

**Comment by amanganiello90** [comment]
Hi @deepu105, 
you can view the app generated with oauth2 [here](https://github.com/jhipster/jhipster-sample-app-nodejs/tree/feature/oauth2).

**Comment by deepu105** [comment]
Cool man. @mraible this should be interesting to you

**Comment by amanganiello90** [comment]
Thanks a lot, for the next days after my other tests, I will release this :) ..@mraible I have fulfilled your as promised ;)

**Comment by amanganiello90** [comment]
Could somebody please create a repo named **jhipster-sample-app-nodejs-oauth2** in order to push the app generated?

**Comment by deepu105** [comment]
Done

**Comment by amanganiello90** [comment]
Thanks @deepu105 .. could you please give me write permission?

**Comment by amanganiello90** [comment]
$200 bug bounty claim: https://opencollective.com/generator-jhipster/expenses/11098

**Comment by jdubois** [comment]
@mraible do you have time to check that this works well?

**Comment by deepu105** [comment]
I have added you to that repo @amanganiello90

**Comment by amanganiello90** [comment]
Thanks @deepu105... @mraible you can check now on [this repo](https://github.com/jhipster/jhipster-sample-app-nodejs-oauth2). The options used are Oauth2 and React client (preferred by @ameinabdi)

**Comment by mraible** [comment]
I took a quick look. I like it! Especially since it uses Okta by default. :)

However, we should probably do Keycloak by default like the default JHipster does.

**Comment by amanganiello90** [comment]
Thanks @mraible ! .For kaycloack there is [another ticket](https://github.com/jhipster/generator-jhipster-nodejs/issues/64) in the kanban board. but before this, I have to enable docker images for the full nodejs app.
> 
> I took a quick look. I like it! Especially since it uses Okta by default. :)
> 
> However, we should probably do Keycloak by default like the default JHipster does.

**Comment by amanganiello90** [comment]
Any news? So that I step to release

**Comment by amanganiello90** [comment]
@mraible, @deepu105, @jdubois , any news?

**Comment by deepu105** [comment]
I think @mraible is the best person to review

**Comment by deepu105** [comment]
I think you should proceed to merge and release

**Comment by mraible** [comment]
I don't have time to test this right now. I trust your judgment. If you say it works, I believe you.

**Comment by amanganiello90** [comment]
Thanks @mraible !

**Comment by deepu105** [comment]
Don't forget to claim the bounty. You deserve it :)

Thanks & Regards,
Deepu

**Comment by amanganiello90** [comment]
Thanks @deepu105, the bounty claim it's already in pending [in this comment](https://github.com/jhipster/generator-jhipster-nodejs/issues/52#issuecomment-546491044)

**Comment by jdubois** [comment]
Hey @amanganiello90 I just wanted to check if you did this bug bounty claim for this ticket: https://opencollective.com/generator-jhipster/expenses/24513 (I don't want anybody else claiming it)

**Comment by amanganiello90** [comment]
> Hey @amanganiello90 I just wanted to check if you did this bug bounty claim for this ticket: https://opencollective.com/generator-jhipster/expenses/24513 (I don't want anybody else claiming it)

HI @jdubois, sorry the description is wrong,  the related issue is on the title (#113)
