### ISSUE TITLE
Update to generator-jhipster v8.7.3

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-nodejs#538]
Update to latest JHipster version.

Like https://github.com/jhipster/generator-jhipster/issues/27764 nodejs uses a different structure.

Node blueprint uses workspaces.
A workspace (folder with package.json) for client and another for server.
A root package.json with prettier and scripts.

- Eslint should be updated to v9 (mandatory since server is a node package too).
- main generator may need adjusts to make it compatible with nodejs structure.

**Comment by mshima** [comment]
@DanielFran bug bounty claim https://opencollective.com/generator-jhipster/expenses/228475

**Comment by DanielFran** [comment]
@mshima approved
