### ISSUE TITLE
i can't start the server

### ISSUE THREAD

**Issue by ameinabdi** [jhipster/generator-jhipster-nodejs#54]
i can't run project i have generate i think their is missing port of server but i didn't get that 

![Screenshot 2019-09-23 at 7 28 10 AM](https://user-images.githubusercontent.com/31644919/65401945-e7e6a080-ddd3-11e9-96a8-8fd5974ec0bf.png)

**Comment by amanganiello90** [comment]
Hi @ameinabdi,
Could you please give me every command that you have run?
Then, check in the **server/src/config/application-dev.yml** or **server/src/config/application-prod.yml**  the server port parameter value.
Please use, for the next opening ticket, the issue template in order to write the clear problem, otherwise for me it's invalid. Thanks!

**Comment by ameinabdi** [comment]
first i have generated project using this command

jhipster --blueprint nodejs

then go to server folder
cd server/

then start project using this command

npm start

**Comment by amanganiello90** [comment]
Ok. But what kind of app you ever generated? (**ApplicationType**).
Then, check in the server/src/config/application-dev.yml the server port parameter value.

**Comment by ameinabdi** [comment]
yes it works thanks a lot mr @amanganiello90  but i have two question can i use react for client side if it is yes. what i do to integrate it and the second one is did you make documentation about how to use this generator thank you

**Comment by amanganiello90** [comment]
> 
> 
> yes it works thanks a lot mr @amanganiello90 but i have two question can i use react for client side if it is yes. what i do to integrate it and the second one is did you make documentation about how to use this generator thank you

Ok thanks. 
Here my questions and answered:
* Could you tell me what was the issue? it is missed the server port value, or the value was of a busy port?
* You can choose react as client answer question, it should work but I have not tested yet.
* For documentation refers to _README.md_  and the _server/README.md_. There are all references and link to framework (NestJS) and usage.

**Comment by ameinabdi** [comment]
yes it was missed the server port value. there is no any value in port 
![Screenshot 2019-09-23 at 2 32 27 PM](https://user-images.githubusercontent.com/31644919/65422491-4aa95d80-de0f-11e9-9393-b9393ee32989.png)

**Comment by amanganiello90** [comment]
Ok. But what kind of app did you generate? (ApplicationType) ??

**Comment by ameinabdi** [comment]
it was monolithic application

**Comment by amanganiello90** [comment]
Ok thanks, I will check.

**Comment by amanganiello90** [comment]
Thansk, I have fixed it [here](https://github.com/jhipster/generator-jhipster-nodejs/commit/775f5b58eadbea811b60157d59355c77aeb57248)
