### ISSUE TITLE
it doesn't generate new entity 

### ISSUE THREAD

**Issue by ameinabdi** [jhipster/generator-jhipster-nodejs#56]
when i finish entering of feild of new Entity it give me back this error 
![Screenshot 2019-09-24 at 9 12 51 AM](https://user-images.githubusercontent.com/31644919/65491995-cca19100-deb8-11e9-9d80-c1fe12199211.png)

**Comment by amanganiello90** [comment]
It is missing a column after AuthModule.

**Comment by venkataramkishore** [comment]
After generating an application using the nodejs blueprint, I have tried to create entities using import-jdl command. I can see error while trying to build using enum as follows:

![image](https://user-images.githubusercontent.com/14111132/65576400-7fdcb980-df8f-11e9-942a-31a1df94a801.png)

**Comment by amanganiello90** [comment]
@venkataramkishore,
Thanks for the feedback. Please use the related template issue to open a bug ticket. This is a issue closed of another topic.
