### ISSUE TITLE
Enum generation error for import-jdl

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#57]
**Describe the bug**
related to #56 in the [comment](https://github.com/jhipster/generator-jhipster-nodejs/issues/56#issuecomment-534881917)

**To Reproduce**
> jhipster import-jdl <my-file.jh> --blueprints nodejs

**Expected behavior**
Correct generation without error

**Additional context**
The error is that missing in utils the [buildEnumInfo](https://github.com/jhipster/generator-jhipster-nodejs/blob/9787a64234303f95b18385cc4f7c3a61e8ef6ca1/generators/entity-server/files.js#L149) function.

**Comment by amanganiello90** [comment]
Hi @venkataramkishore,
you can try with your jdl if the bug is resolved. 
Follow the [CONTRIBUTING.MD](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/CONTRIBUTING.md) and checkout on **feature/no-maven** branch for the generator-blueprint-nodejs

**Comment by venkataramkishore** [comment]
Hi @amanganiello90,
Following are the steps i have followed:
> git clone <repo>
>cd generator-jhipster-nodejs
generator-jhipster-nodejs>git branch --list 
*master
generator-jhipster-nodejs>git checkout --track -b feature/no-maven
generator-jhipster-nodejs>git pull
Already up-to date
generator-jhipster-nodejs>git branch --list
*feature/no-maven
master
generator-jhipster-nodejs>cd generator-jhipster-nodejs
generator-jhipster-nodejs> npm install
generator-jhipster-nodejs> npm link generator-jhipster

> cd..
> cd myproject
myproject>jhipster import-jdl <file>.jh --blueprint nodejs

** I have new error cannot find module 'read-pkg-up'**

![image](https://user-images.githubusercontent.com/14111132/65665620-9c452880-e059-11e9-9d2e-1de4de082aa0.png)

![image](https://user-images.githubusercontent.com/14111132/65665678-bb43ba80-e059-11e9-87e4-3a0a1111a922.png)

![image](https://user-images.githubusercontent.com/14111132/65665755-ea5a2c00-e059-11e9-8c8a-7e3329c56388.png)

![image](https://user-images.githubusercontent.com/14111132/65665821-0362dd00-e05a-11e9-8a11-5687ae4d4822.png)

**Comment by amanganiello90** [comment]
Hi @venkataramkishore,
the last commands are wrong. Following these:

```
    git clone
    cd generator-jhipster-nodejs
    generator-jhipster-nodejs>git branch --list
    *master
    generator-jhipster-nodejs>git checkout --track -b feature/no-maven
    generator-jhipster-nodejs>git pull
    Already up-to date
    generator-jhipster-nodejs>git branch --list
    *feature/no-maven
    master
    generator-jhipster-nodejs>cd generator-jhipster-nodejs
    generator-jhipster-nodejs> npm install
    generator-jhipster-nodejs> npm link 

    cd..
    cd myproject
    myproject>npm link generator-jhipster
   myproject>npm link generator-jhipster-nodejs
    myproject>jhipster import-jdl .jh --blueprint nodejs
```

**Comment by venkataramkishore** [comment]
when generating it takes sqllite only for development, no other choice yet. I have enums for my entities to generate. As you suggest enum doesnot work
I still have tried your steps with enums in jdl and i have the following error 

![image](https://user-images.githubusercontent.com/14111132/65762745-519ddc00-e13f-11e9-8bd3-7bfde22388ce.png)

**Comment by amanganiello90** [comment]
Hi @venkataramkishore ,
before npm link you have to perform npm install on generator-jhipster-nodejs and generator-jhipster projects.
I will check and track the prodDatabase choose in another issue. Thanks.
