### ISSUE TITLE
Language i18n for react home page translation NHipster

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#59]
If we choose the internationalization answer, the default html home page for NHipster is translated. So it is needed to override also the languages json files for NHipster in React client.

**Comment by amanganiello90** [comment]
First Steps:
1. Enable i18n deleting [these configuration](https://github.com/jhipster/generator-jhipster-nodejs/blob/bd6f3cf9ba5b9d8ffb5ed2abb98b03a6301514a6/generators/app/index.js#L91)
2. Create a [entity-i18n subgenerator](https://github.com/jhipster/generator-jhipster/tree/master/generators/entity-i18n) in Nhipster

**Comment by Aragonbn90** [comment]
I've forked the repository. This issue will be at https://github.com/Aragonbn90/generator-jhipster-nodejs/tree/i18n-react-home

**Comment by amanganiello90** [comment]
Great!!! you are wonderful!

**Comment by amanganiello90** [comment]
For the previous second step, it must be replaced with the languages subgenerator.

**Comment by amanganiello90** [comment]
![language](https://user-images.githubusercontent.com/20536757/90239680-38ba1a00-de28-11ea-8fa2-54673f2f15cb.png)
