### ISSUE TITLE
No entity menu in react client

### ISSUE THREAD

**Issue by ameinabdi** [jhipster/generator-jhipster-nodejs#62]
i got this error when i login 
![Screenshot 2019-09-30 at 20 51 07](https://user-images.githubusercontent.com/31644919/65903326-ea915900-e3c4-11e9-9887-73776caa6fd4.png)

**Comment by amanganiello90** [comment]
This is related to #46.  Thanks for the feedback.

**Comment by amanganiello90** [comment]
I have tested react client, and with my [example-1.jh](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/examples-jdl/example-1.jh) works. Now I'm testing the CRUD operations for the new entities.

**Comment by ameinabdi** [comment]
when i generate with your example-1.jh and run the server. it is not running it show me error of entity of user. i take all steps of readme but it doesn't. so could you please answer few question 
1. what machine did you use for generating ?
2. what database did you use in development ?
3. is their any extra step you use when you generate project ?
4. can i connect my nodejs project and react-native jhipster project ?

![Screenshot 2019-10-11 at 09 14 25](https://user-images.githubusercontent.com/31644919/66628647-12c05980-ec08-11e9-9bcb-84fc9cb81aab.png)

**Comment by amanganiello90** [comment]
Single-course.model it's the old name of the entity... now it's single-course.entity. You have to upgrade the generator.

**Comment by amanganiello90** [comment]
Please wait the next release in order to retry my jdl generation. After reopen a new issue with your questions.

**Comment by ameinabdi** [comment]
ok thank you @amanganiello90  when did you release next one ?

**Comment by amanganiello90** [comment]
> 
> 
> ok thank you @amanganiello90 when did you release next one ?

Maybe in this weekend, I have to review doc and examples #65

**Comment by ameinabdi** [comment]
did you release ? @amanganiello90

**Comment by amanganiello90** [comment]
Yes

**Comment by ameinabdi** [comment]
good but still error exist

**Comment by amanganiello90** [comment]
Hi @ameinabdi,
use my [example-1.jh](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/examples-jdl/example-1.jh).

So run 
```
jhipster --blueprints nodejs import-jdl example-1.jh
```
Go for example in chrome using **localhost:8081**.
After login, there will be two entities in the related menu:

![immagine](https://user-images.githubusercontent.com/20536757/66736509-a5abfe80-ee69-11e9-883e-899dca5c0e68.png)

**Comment by ameinabdi** [comment]
i get same error when i flow your guide. is their is any other ways please

**Comment by amanganiello90** [comment]
Do you have in **src\main\webapp\app\entities** the entities?
![immagine](https://user-images.githubusercontent.com/20536757/66747215-490a0d00-ee84-11e9-98e3-bcfceaf46bd7.png)

**Comment by ameinabdi** [comment]
yes 
![Screenshot 2019-10-14 at 14 13 49](https://user-images.githubusercontent.com/31644919/66747309-e1a48b00-ee8c-11e9-925a-f05db047031d.png)

**Comment by ameinabdi** [comment]
could you please access my computer and generate new one ?

**Comment by amanganiello90** [comment]
> 
> 
> could you please access my computer and generate new one ?

Commit your project in a github repo and I will commit my generation in other branch. So we can compare the generations.

**Comment by ameinabdi** [comment]
https://github.com/ameinabdi/biiloffice

**Comment by amanganiello90** [comment]
> 
> 
> this is repo
> 
> https://github.com/ameinabdi/biiloffice

I still see the maven wrapper. You have not updated the nodejs blueprint.
Please run ```npm i -g generator-jhipster-nodejs```.
After delete all your projects and run the steps of https://github.com/jhipster/generator-jhipster-nodejs/issues/62#issuecomment-541540486.
