### ISSUE TITLE
Support blob types for the entity

### ISSUE THREAD

**Issue by ameinabdi** [jhipster/generator-jhipster-nodejs#68]
i added my jdl ImageBlog but it tells me that image Is not Support mysql database

could you please fix that error or is their any other way to use image field ?

**Comment by amanganiello90** [comment]
Hi @ameinabdi, TypeORM supports blob for some database types. For mysql there is the **image** type, as you can read [here](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#column-types-for-mssql)... so replace your colulm entity with that ;)

**Comment by ameinabdi** [comment]
hi @amanganiello90 
okey i have another question
-> is there  any way to make relations of entities

**Comment by amanganiello90** [comment]
Hi @ameinabdi ... so All it's possible for the software engineering, but the time it's only 24 hours per day, and I'm developing almost everything in this project. That you explain is a new feature, but now I haven't time to implement it, I have just finished the oauth2 feature also for the react client..
So if somebody wants to contribute, with a donation or a code development, is welcome!

**Comment by ameinabdi** [comment]
sorry for using your time @amanganiello90  
i would like to contribute as code development if you guide me 
thank you

**Comment by amanganiello90** [comment]
Hi @ameinabdi , it's not a problem! I will show you what you have to change, and after that push the your branch openind a pull request for me.

For this feature, you have to modify the [entity.ts template](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/generators/entity-server/templates/server/src/domain/entity.ts.ejs#L101) adding maybe an if for your type.. but please attention that according typeorm, the blob type is different for every database, so you have to include also a condition with the **prodDatabaseType**.
You can find examples in the [jhipster entity template](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs).

To develop the feature, follow this steps:

- ```git clone https://github.com/jhipster/generator-jhipster-nodejs.git```
- ```cd generator-jhipster-nodejs```
- ```git checkout -b feature/blob```
- ```npm install``` 
- ```npm link```
- ```cd ..```
- ```git clone https://github.com/jhipster/generator-jhipster.git```
- ```cd generator-jhipster```
- ```npm install``` 
- ```npm link```
- ```cd ..```
- ```mkdir test-generation```
- ```cd test-generation```
- ```npm link generator-jhipster```
- ```npm link generator-jhipster-nodejs```

Now you will develop under the **generator-jhipster-nodejs** that you have cloned with git.
After finish, to generate the app and check your feature, run in **test-generation** folder:

- ```jhipster --blueprints nodejs import-jdl <your-jdl>```

**Comment by amanganiello90** [comment]
The image type is used only for [mssql](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#column-types-for-mssql) and not for *mysql*.
So I will start feature on [feature/blob-entity  branch](https://github.com/jhipster/generator-jhipster-nodejs/tree/feature/blob-entity) to include generic *blob type*
