### ISSUE TITLE
After choosing Postgres as the production DB the production type in orm.config.ts is set as postgresql and gives  an error

### ISSUE THREAD

**Issue by robconnell9** [jhipster/generator-jhipster-nodejs#70]
**Describe the bug**
When there is a prompt for the production database and postgresql is chosen this populates orm.config.ts with the prod database type of postgresql at line 28. This value should be postgres as per the value in PostgresConnectioOptions.d.ts

**To Reproduce**
jhipster --blueprint nodejs
choose monolithic
choose postgresql for production database

**Expected behavior**
value in orm.config.ts should be postgres.

**Screenshots**
not required

**Desktop (please complete the following information):**
IOS
Chrome
current as per 26/10/19

**Smartphone (please complete the following information):**
NA

**Additional context**
Supplied as required

**Comment by amanganiello90** [comment]
Thanks! I have fixed that... could you try with the bugfix branch [here](https://github.com/jhipster/generator-jhipster-nodejs/tree/bug/postegres)?

**Comment by robconnell9** [comment]
I tried to install the specific branch using:

npm install -g
https://github.com/jhipster/generator-jhipster-nodejs/tree/bug/postegres

which was complaining about a missing package.json. Any ideas ?

**Comment by amanganiello90** [comment]
Hi @robconnell9 ,
you have to follow this steps:

- git clone https://github.com/jhipster/generator-jhipster-nodejs.git
- cd generator-jhipster-nodejs
- git checkout bug/postegres
- npm install 
- npm link
- cd ..
- git clone https://github.com/jhipster/generator-jhipster.git
- cd generator-jhipster
- npm install 
- npm link
- cd ..
- mkdir test-generation
- cd test-generation
- npm link generator-jhipster
- npm link generator-jhipster-nodejs
- jhipster --blueprints nodejs

These are the steps written in the [CONTRIBUTING GUIDE](https://github.com/jhipster/generator-jhipster-nodejs/blob/master/CONTRIBUTING.md).

**Comment by robconnell9** [comment]
I followed the steps and this fixes the problem that I raised

**Comment by amanganiello90** [comment]
Good! thanks for the collaboration! You are welcome to contribute with a donation or with the development of new features, and introduce new people in this project/community :)
