### ISSUE TITLE
Support mongodb generation with docker image (without relationship)

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#73]
As explained in the title, we have to provide mongodb entity generation only for prod running, without go in conflict with sqlite dev database.

**Comment by amanganiello90** [comment]
According #148 , I change this issue in order to implement mongodb as dev and prod db (so including a dockerized container).

**Comment by MattLish** [comment]
Can you try to give an overview of the work required to do this?
I am new to jhipster so I am not sure what needs doing.
If you can give an overview, I might be able to help out adding it.
(Or if not me, someone might be able to help)

**Comment by amanganiello90** [comment]
Then, you can try to build a sample app with mongodb.
For this fork the [sample nodejs app](https://github.com/jhipster/jhipster-sample-app-nodejs).
After that you have to do some changes to run the app with mongodb:
1 - Modify [typeOrmConfig](https://github.com/jhipster/jhipster-sample-app-nodejs/blob/master/server/src/orm.config.ts) with mongodb endpoint. You can use a free online instance from https://mlab.com/
2- Fix eventual error for entity model ts files, There is an example: https://github.com/typeorm/mongo-typescript-example
3- You have to run jhipster nodejs entity generator on the app in order to create a CRUD api entity to test the repository operations.

For other questions fell free to ask me. Thanks

**Comment by mayankgirdhar** [comment]
Is there any chance to get MongoDB support soon?

**Comment by amanganiello90** [comment]
Hi @mayankgirdhar, could you contribute?

**Comment by mayankgirdhar** [comment]
Hello @amanganiello90 yes I am ready to do. It will be a good opportunity for me to contribute.

**Comment by amanganiello90** [comment]
Feature started on [feature/issue73-mongo branch](https://github.com/jhipster/generator-jhipster-nodejs/tree/feature/issue73-mongo).
We can consider for development the [mongodb-memory-server](https://earrieta.dev/mocking-our-mongodb-while-testing-in-nestjs-ck1a316df00izjfs1adaw9li6)

**Comment by amanganiello90** [comment]
There are some problems with the relationship. I have opened an issue to ask more: https://github.com/typeorm/typeorm/issues/7258

**Comment by amanganiello90** [comment]
I will work on this feature without supporting relationship. So if in the jdl model or entity generation there is a relationship declaration, the generator will raise an error and stops it
