### ISSUE TITLE
Support code quality and coverage reports on SonarCloud for the generator

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-nodejs#85]
It can be useful to have reports about quality and coverage issue of the generator.
For travis is simple to integrate [code climate](https://medium.com/makers-team-coad/how-to-ace-test-coverage-code-quality-code-style-using-travis-ci-and-code-climate-afde0eb2f007).
@deepu105, @pascalgrimaud and @jdubois any suggestions?

**Comment by jdubois** [comment]
- we have a free account on SonarQube and use it for the Java builds, could you have a look? In https://www.jhipster.tech/code-quality/
- please note we are moving away from Travis to GitHub Actions

**Comment by amanganiello90** [comment]
So I can configure and publish reports on the same SonarQube account? in the link of the jhipster page it explains how to use a SonarQube from the docker image.
GitHub Actions supports anythings, such as [github code climate](https://github.com/marketplace/code-climate), but it is not free. Generally every blueprint use travis-ci, so I have extended the standard plan with another stages for unit tests and integration-tests: https://github.com/jhipster/generator-jhipster-nodejs/blob/4e7a12545e410b90917d8964bd6ccd08b52065c9/.travis.yml

**Comment by jdubois** [comment]
On the JHipster SonarQube organization I need to create one project for you (or several!), and then there's a secret token to configure. So a little work from me, but nothing big.

**Comment by amanganiello90** [comment]
As you prefer @jdubois, no problems for me :) ... Otherwise I use another open source tool for code analysis.

**Comment by pascalgrimaud** [comment]
@amanganiello90 : for your information, we removed Travis in main generator-jhipster, so I think all projects in the organization should migrate to GitHub Actions as it's far better than Travis

Then, for Code Analyze, I'd prefer to keep consistency, so let's use SonarCloud at https://sonarcloud.io/organizations/jhipster/projects and then:
- create a new project at SonarCloud
- add SONAR_TOKEN directly in GitHub Actions
- add analyze task in GitHub Actions workflow

**Comment by amanganiello90** [comment]
ok @pascalgrimaud. But now I haven't grants to create project on SonarCloud. So after migrating pipeline on github actions you can give me the sonar token to add on it? (or you add directly that). Thanks.

**Comment by pascalgrimaud** [comment]
@amanganiello90 : to understand well, is it for analyzing the blueprint `generator-jhipster-nodejs` or a generated project with this blueprint like https://github.com/jhipster/jhipster-sample-app-nodejs ?

**Comment by amanganiello90** [comment]
> 
> 
> @amanganiello90 : to understand well, is it for analyzing the blueprint `generator-jhipster-nodejs` or a generated project with this blueprint like https://github.com/jhipster/jhipster-sample-app-nodejs ?

For now it for the generator. Next we will configure also SonarCloud for the sample apps and for the generated projects (we have before to resolve #83 and #55).

**Comment by pascalgrimaud** [comment]
Just created: https://sonarcloud.io/dashboard?id=jhipster_generator-jhipster-nodejs
I added a SONAR_TOKEN in GitHub Actions secrets too.

If it doesn't work, just tell me, and I can regenerate one and update the SONAR_TOKEN in GitHub.

**Comment by amanganiello90** [comment]
Thanks a lot! I have justed finished the pipelines migration from Travis to GitHub Actions

**Comment by amanganiello90** [comment]
@pascalgrimaud  have you added the GITHUB_TOKEN secret? The build said that I don't have grants to run sonar analysis...

https://github.com/jhipster/generator-jhipster-nodejs/commit/139b72611675ab3d9efc2183853742c50173fbbf/checks?check_suite_id=381769719

**Comment by pascalgrimaud** [comment]
You need to have these lines in your yaml file:
https://github.com/jhipster/generator-jhipster/blob/master/.github/workflows/angular.yml#L162-L164

Is it the case ?
Otherwise, the steps won't have any secret var

**Comment by amanganiello90** [comment]
Yes, the variables are necessary because github actions told me that before missing.

I have this sonar properties: https://github.com/jhipster/generator-jhipster-nodejs/blob/feature/sonar-generator-publish/sonar-project.properties

And yml configuration:
https://github.com/jhipster/generator-jhipster-nodejs/blob/139b72611675ab3d9efc2183853742c50173fbbf/.github/workflows/generator.yml#L23

But I have the error: 

```
INFO: Analysis report generated in 155ms, dir size=153 KB
INFO: Analysis report compressed in 48ms, zip size=44 KB
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 39.149s
ERROR: Error during SonarQube Scanner execution
INFO: Final Memory: 28M/97M
ERROR: You're not authorized to run analysis. Please contact the project administrator.
```

**Comment by pascalgrimaud** [comment]
It's normal as the sonar.login (which is the SONAR_TOKEN) is not correct:
https://github.com/jhipster/generator-jhipster-nodejs/blob/feature/sonar-generator-publish/sonar-project.properties#L6

You need to remove this line, I think

**Comment by amanganiello90** [comment]
I copied the properties from SonarCloud project wizard, and I immagine that maybe it was not right with SONAR_TOKEN. So now I remove it

**Comment by pascalgrimaud** [comment]
Following your work in the `feature/sonar-generator-publish branch`, it looks ok:
http://localhost:9001/dashboard?id=jhipster_generator-jhipster-nodejs

I suggest to only add the analyze for master branch
So you need to add a condition for that

**Comment by amanganiello90** [comment]
Yestarday I test all and it's ok, I have added also the github badges on the README.md
If I merge on master, then is it analized?

**Comment by pascalgrimaud** [comment]
Yes, you can merge it.
But if you create a new branch, the result from this new branch will erase the current result from master -> that's why I think the analyze should be done only for master branch

**Comment by amanganiello90** [comment]
I saw that on Sonar you can switch analysis on the related branch:
![immagine](https://user-images.githubusercontent.com/20536757/71714767-66a99b80-2e0f-11ea-8bf3-b81692291cf6.png)

**Comment by amanganiello90** [comment]
@pascalgrimaud thanks for the helping. Now it's all perfect :)

**Comment by pascalgrimaud** [comment]
I though the branch analysis were only for the paid one version
So in this case, it's perfect !

Now for contributors, which won't have SONAR_TOKEN in their GitHub fork repo, I think you should exclude the analysis if it's in a fork.
Otherwise, our contributors will have failed builds:
https://github.com/pascalgrimaud/generator-jhipster-nodejs/commit/efc7e86e05df0d72c131f39141ab804ced6366ee/checks?check_suite_id=382839091

**Comment by amanganiello90** [comment]
ok @pascalgrimaud , I have just added the exclusion and it works: https://github.com/jhipster/generator-jhipster-nodejs/commit/5aabd28ef8178a261dfab447b419b21eaf4ac350
