### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'XXXXX\server\src\config/application-d.yml'

### ISSUE THREAD

**Issue by ajoysinhaabbvie** [jhipster/generator-jhipster-nodejs#96]
**Describe the bug**
After creation of nodebased microservice using **jhipster import-jdl model-name.jdl --blueprints nodejs**, on start of server "npm start" application is looking for a file name application-**d**.yml. where as application-**dev**.yml

**To Reproduce**
1. Create a nodejs app using jhipster import-jdl model-name.jdl --blueprints nodejs
2. go into server folder
3. run npm install
4. run npm start 

Application is giving error as below
[nodemon] starting `ts-node src/main.ts`
Error: ENOENT: no such file or directory, open 'D:\microservices\services\usermicroservice\server\src\config/application-d.yml'

**Expected behavior**
application should start

Note : if you change the application-**dev**.yml into application-**d**.yml, then application is starting smoothly

**Comment by amanganiello90** [comment]
Hi @ajoysinhaabbvie,
thanks to use NHipster.. every feedback is very important.
So, can you explain what version of blueprint are you using?
The last release passed every integration test that covers your use case: https://github.com/jhipster/generator-jhipster-nodejs/runs/384846320

**Comment by ajoysinhaabbvie** [comment]
I am using : generator-jhipster-nodejs@1.0.0-beta.2
I have created nodejs microservice app from jdl file. and then run the application server.
attaching the screenshots for your reference .. hope this will help ..

If i do rename application-dev.yml to application-d.yml then system is working .

![screenshot1](https://user-images.githubusercontent.com/50991311/72869999-e939c280-3d0c-11ea-83d2-aa25a0f2d137.PNG)
![screenshot2](https://user-images.githubusercontent.com/50991311/72870000-e9d25900-3d0c-11ea-8b9d-26ba397de2a6.PNG)

**Comment by ajoysinhaabbvie** [comment]
Attaching jdl file for your reference 
Change name from .txt to .jdl

[app.jdl.txt](https://github.com/jhipster/generator-jhipster-nodejs/files/4095576/app.jdl.txt)

**Comment by amanganiello90** [comment]
Maybe I have understand your problem.. Can you check what is the value of the node system variable **NODE_ENV**? It is used in the app starting: https://github.com/jhipster/generator-jhipster-nodejs/blob/927622480140e64c12437c0f979ab8f64c1f8f69/generators/server/templates/server/src/config/config.ts.ejs#L91

So to change it you can rewrite value in your (env project file)[https://github.com/jhipster/generator-jhipster-nodejs/blob/v1.0.0-beta.2/generators/server/templates/server/.env.ejs]

**Comment by amanganiello90** [comment]
Hi @ajoysinhaabbvie, any news???

**Comment by kosnkow** [comment]
we had the same problem so we changed:
-const yamlConfig = yaml.safeLoad(fs.readFileSync(__dirname + '/application.yml', 'utf8'));
-const envYamlConfig = yaml.safeLoad(fs.readFileSync(__dirname + `/application-${process.env.NODE_ENV}.yml`, 'utf8'));
+const yamlConfig = yaml.safeLoad(fs.readFileSync(__dirname + '/../../config/application.yml', 'utf8'));
+const envYamlConfig = yaml.safeLoad(fs.readFileSync(__dirname + `/../../config/application-${process.env.NODE_ENV}.yml`, 'utf8'));

**Comment by amanganiello90** [comment]
It is linked to #99 that has more details.

**Comment by amanganiello90** [comment]
Fix with #102 , I will release the 1.0.0-beta.3

**Comment by amanganiello90** [comment]
Hi @ajoysinhaabbvie and @kosnkow ,
you can test the new version just published 1.0.0-beta.3. Feel free to open new issues if there are another problems. Thanks!
